---
title: "Tableau de bord - Indices insee"
output: 
  flexdashboard::flex_dashboard:
    logo: images/logo.png
    theme: flatly
    orientation: rows
    social: menu
    source_code: embed
---


```{r}
library(highcharter)
library(dplyr)
library(viridisLite)
library(forecast)
library(treemap)
library(flexdashboard)
library(data.table)
library(reshape2)
library(xts)
library(dygraphs)
library(ggplot2)

```


```{r}
indice=read.csv2("data/Indices/indice.csv")
data=data.table(indice)
data$date=paste(data$Annee,data$Mois,"01",sep="-")

ts=xts(as.numeric(data$Indice),order.by = as.Date(data$date),frequency = 30.4)
tsc=xts(as.data.frame(dcast(data,Mois~Annee))[,-1],
        order.by = seq.Date(from = as.Date("2016/1/1"),to=as.Date("2016/12/31"),by="month"),
        frequency = 30.4)
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------
### Evolutions temporelles

```{r}

dygraph(ts) %>%
  dyRoller(rollPeriod = 1)%>%
  dyRangeSelector(height = 30)

```

### Evolutions temporelles par mois

```{r}
dygraph(tsc) %>%
  dyRoller(rollPeriod = 2)%>%
  dyRangeSelector(height = 30)
```

### Prévision

```{r}
f=forecast(ts(ts,frequency=12,start=c(1990,1)),level = 90)
fd=cbind(f$x,f$mean,f$lower,f$upper)
colnames(fd)=c("historique","prevision","borne inf","borne sup")

dygraph(fd) %>%
  dyRoller(rollPeriod = 1)%>%
  dyRangeSelector(height = 20)

```


### Test Highchart

```{r}

thm <- 
  hc_theme(
    colors = c("#1a6ecc", "#434348", "#90ed7d"),
    chart = list(
      backgroundColor = "transparent",
      style = list(fontFamily = "Source Sans Pro")
    ),
    xAxis = list(
      gridLineWidth = 1
    )
  )


ts(ts,frequency=12,start=c(1990,1)) %>% 
  forecast(level = 90) %>% 
  hchart()%>% 
  hc_add_theme(thm)

```



Row {.tabset .tabset-fade}
-----------------------------------------------------------------------
### Evolutions des taux mensuels

```{r}
mens=diff(ts)/stats::lag(ts,k=1)
dygraph(mens)%>%
  dyRoller(rollPeriod = 1)%>%
  dyRangeSelector(height = 30)

```

### Prévision des taux mensuels

```{r}
ts(mens[is.na(mens)==FALSE,],frequency=12) %>% 
  forecast(level = 90) %>% 
  hchart()

```

### Evolutions des taux annuels

```{r}
annu=diff(ts,12)/stats::lag(ts,k=12)
dygraph(annu)%>%
  dyRoller(rollPeriod = 1)%>%
  dyRangeSelector(height = 30)

```

### Prévision des taux annuels

```{r}
ts(annu,frequency=12) %>% 
  forecast(level = 90) %>% 
  hchart()

```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Evolution des taux de décembre

```{r}
dec=ts[.indexmon(ts)==11,]
dygraph(diff(dec)/stats::lag(dec,k=1)) %>%
  dyRangeSelector(height = 20)
```

### Prévision des taux de décembre

Remarque: prévision des taux à partir des prévision des indices mensuels. Il est également possible de travailler sur les taux mensuels.

```{r}

prev=rbind(ts,f$mean)
decp=prev[.indexmon(prev)==11,]

dygraph(diff(decp)/stats::lag(decp,k=1)) %>%
  dyRangeSelector(height = 20)

```

