---
title: "Tableau de bord - Indices insee"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    logo: images/logo.png
    theme: cosmo
---



```{r}
# install.packages("flexdashboard")
# install.packages("dygraphs")
# install.packages("forecast")
library(highcharter)
library(dplyr)
library(viridisLite)
library(forecast)
library(treemap)
library(flexdashboard)
library(data.table)
library(reshape2)
library(xts)
library(dygraphs)
library(ggplot2)
library(plotly)
```


```{r}
indices=read.csv2("data/Indices/indices_annuels.csv")
indices=read.csv2("data/Indices/indices_annuels2.csv")
indices=as.matrix(indices)

# colnames(indices)
# data=data.table(indices)
# data[,Year:=NULL]

taux=diff(indices)/indices[-nrow(indices),]

ind_n=indices/matrix(rep(indices[1,],nrow(indices)),nrow(indices),ncol(indices),byrow = TRUE)*100
ind_n[,1]=indices[,1]

indts_n=xts(ind_n[,-1],order.by = as.Date(paste(indices[,"Year"],"/12/31",sep="")),frequency = 365)
indts=xts(indices[,-1],order.by = as.Date(paste(indices[,"Year"],"/12/31",sep="")),frequency = 365)

tauxts=xts(taux[,-1],order.by = seq(as.Date("2000/12/31"), as.Date("2015/12/31"), by = "year"),frequency = 365)

```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------
### Evolutions temporelles

```{r}

dygraph(indts) %>%
  dyRoller(rollPeriod = 1)%>%
  dyRangeSelector(height = 30)

```

### Evolutions temporelles

```{r}

dygraph(indts_n) %>%
  dyRoller(rollPeriod = 1)%>%
  dyRangeSelector(height = 30)

```

### Taux annuels

```{r}

dygraph(tauxts) %>%
  dyRoller(rollPeriod = 1)%>%
  dyRangeSelector(height = 30)

```

### Plotly

```{r}
indices=data.table(indices)
DT=melt(indices,id.vars="Year")
p=ggplot(data = DT,aes(x=Year,y=value,color=variable))+geom_line()
ggplotly(p)
```


### Plotly

```{r}
ind_n[,"Year"]=seq(1999,2015,1)

ind_n=data.table(ind_n)
DT=melt(ind_n,id.vars="Year")
p=ggplot(data = DT,aes(x=Year,y=value,color=variable))+geom_line()
ggplotly(p)
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Composition

```{r}
ggplot(data = melt(as.data.frame(indices),id.vars="Year"),aes(as.factor(Year),value,fill=variable))+
  geom_bar(stat = "identity",position = "fill")


ggplot(data = melt(as.data.frame(ind_n),id.vars="Year"),aes(as.factor(Year),value,fill=variable))+
  geom_bar(stat = "identity",position = "fill")

```

### Composition 2
```{r}

ggplot(data = melt(as.data.frame(indices),id.vars="Year"),aes(as.factor(Year),value,fill=variable))+
  geom_bar(stat = "identity")

ggplot(data = melt(as.data.frame(ind_n),id.vars="Year"),aes(as.factor(Year),value,fill=variable))+
  geom_bar(stat = "identity")


```


