/* L'Île aux Mots : contenu du jeu « Devinettes ». Chaque devinette parle à la première personne (« I am yellow… »).
   w: the answer (English word of the lexicon) · i: pictograms of the three simple clues ("#rrggbb" draws a colour dot)
   no: words that also fit the simple clues, never offered as a wrong picture · who: a person, "Who am I?"
   en/de/lb/zh: "simple 1|simple 2|simple 3|rich 1|rich 2": levels 1 and 2 use the simple clues, 3 and 4 the rich ones.
   Luxembourgish checked word by word on lod.lu (n rule applied: "Ech si giel", "Ech sinn orange"): roden → rot!, wien (who),
   d'Méck (f, a fly) → Mécken, d'Kanéngchen (f) → eng Kanéngchen, d'Strëmp (f) → eng Strëmp, de Fluchhafen, de Schnapp (a cold),
   Zort → villen Zorten, droen → du dréis (to wear), d'Seegel (n). Animal sounds as in the game "Qui fait ce bruit ?" (mu, uhu). */
const DEVINETTES_UI = {
  what: {en:"What am I?", de:"Was bin ich?", lb:"Wat sinn ech?", zh:"我是什么？"},
  who: {en:"Who am I?", de:"Wer bin ich?", lb:"Wien sinn ech?", zh:"我是谁？"},
  again: {en:"Again", de:"Nochmal", lb:"Nach eng Kéier", zh:"再听一次"},
  read: {en:"Read and guess!", de:"Lies und rate!", lb:"Lies a rot!", zh:"读一读，猜一猜！"},
  yes: {en:"Yes! I'm the {w}!", de:"Ja! Ich bin {w}!", lb:"Jo! Ech sinn {w}!", zh:"对啦！我是{w}！"},
  no: {en:"No, that's the {w}. Try again!", de:"Nein, das ist {w}. Versuch es noch mal!", lb:"Neen, dat ass {w}. Probéier nach eng Kéier!", zh:"不对，那是{w}。再试一次！"},
  nos: {en:"No, those are the {w}. Try again!", de:"Nein, das sind {w}. Versuch es noch mal!", lb:"Neen, dat sinn {w}. Probéier nach eng Kéier!", zh:"不对，那是{w}。再试一次！"},
  title: {en:"Riddles", de:"Rätsel", lb:"Räätsel", zh:"猜谜语"},
  sub: {en:"Listen and guess!", de:"Hör zu und rate!", lb:"Lauschter a rot!", zh:"听一听，猜一猜！"}
};
// wrong pictures that are plural in a language (English word of the lexicon): "those are the grapes", "das sind die Trauben"
const DEVINETTES_PL = {en:["grapes","cherries","noodles","eyes","glasses","scissors","shoes","socks","gloves","boots","trousers"],
  de:["grapes","cherries","noodles","eyes","hair","shoes","socks","gloves","boots"], lb:["grapes","cherries","noodles","eyes","hair","shoes","socks","gloves","boots"]};
const DEVINETTES = [
  /* animals */
  {w:"cat", i:"🗣️|🥛|🐭", no:"tiger,lion,mouse", en:"I say meow.|I love milk.|I chase mice.|I have soft paws, and I purr when I am happy.|I sleep a lot, and I always land on my feet.",
   de:"Ich mache miau.|Ich trinke gern Milch.|Ich fange Mäuse.|Ich habe weiche Pfoten, und ich schnurre, wenn ich glücklich bin.|Ich schlafe sehr viel und lande immer auf den Füßen.",
   lb:"Ech miauen.|Ech drénken d'Mëllech gär.|Ech fänken d'Maus.|Ech hu mëll Patten, an ech schnurren, wann ech frou sinn.|Ech schlofe ganz vill, an ech falen ëmmer op d'Féiss.",
   zh:"我会喵喵叫。|我爱喝牛奶。|我会抓老鼠。|我有软软的爪子，开心的时候会呼噜呼噜。|我很爱睡觉，跳下来总是脚先着地。"},
  {w:"dog", i:"🗣️|🦴|⚽", no:"", en:"I say woof woof.|I love bones.|I bring the ball back.|I am your best friend, and I bark when someone knocks at the door.|I wag my tail when I am happy.",
   de:"Ich mache wau wau.|Ich liebe Knochen.|Ich bringe den Ball zurück.|Ich bin dein bester Freund und belle, wenn jemand an die Tür klopft.|Ich wedle mit dem Schwanz, wenn ich mich freue.",
   lb:"Ech billen: wau wau!|Ech hu Schanke gär.|Ech bréngen de Ball zeréck.|Ech sinn däi beschte Frënd, an ech billen, wann een un d'Dier klappt.|Ech wibbele mam Schwanz, wann ech frou sinn.",
   zh:"我会汪汪叫。|我爱啃骨头。|我会把球叼回来。|我是你最好的朋友，有人敲门的时候我会叫。|我高兴的时候会摇尾巴。"},
  {w:"cow", i:"🗣️|🥛|🌿", no:"", en:"I say moo.|I give milk.|I eat grass.|I live on a farm, and I have black and white spots.|I chew grass all day long in the meadow.",
   de:"Ich mache muh.|Ich gebe Milch.|Ich fresse Gras.|Ich lebe auf dem Bauernhof und habe schwarze und weiße Flecken.|Ich kaue den ganzen Tag Gras auf der Wiese.",
   lb:"Ech muen: mu!|Ech gi Mëllech.|Ech iesse Gras.|Ech liewen um Bauerenhaff, an ech hu schwaarz a wäiss Flecken.|Ech knaen de ganzen Dag Gras op der Wiss.",
   zh:"我会哞哞叫。|我给大家牛奶喝。|我吃青草。|我住在农场里，身上有黑白色的斑点。|我整天在草地上嚼青草。"},
  {w:"pig", i:"🗣️|#F48FB1|🟤💦", no:"", en:"I say oink oink.|I am pink.|I love mud.|I have a curly tail and a flat round nose.|I roll in the mud to cool down.",
   de:"Ich mache grunz, grunz.|Ich bin rosa.|Ich liebe Matsch.|Ich habe einen Ringelschwanz und eine flache, runde Nase.|Ich wälze mich im Matsch, um mich abzukühlen.",
   lb:"Ech grunzen.|Ech si rosa.|Ech hunn de Bulli gär.|Ech hunn e krauselege Schwanz an eng flaach, ronn Nues.|Ech wenzele mech am Bulli, fir mech ofzekillen.",
   zh:"我会哼哼叫。|我是粉红色的。|我最爱玩泥巴。|我有一条卷卷的尾巴和一个扁扁的圆鼻子。|我在泥巴里打滚，让自己凉快一点。"},
  {w:"duck", i:"🗣️|🏊|#FB8C00", no:"frog,chicken,bird,penguin", en:"I say quack quack.|I can swim.|I have orange feet.|I swim on the pond, and I have a flat orange beak.|I have feathers, and I can swim, walk and fly.",
   de:"Ich mache quak, quak.|Ich kann schwimmen.|Ich habe orange Füße.|Ich schwimme auf dem Teich und habe einen flachen, orangefarbenen Schnabel.|Ich habe Federn und kann schwimmen, laufen und fliegen.",
   lb:"Ech quaken.|Ech ka schwammen.|Ech hunn orange Féiss.|Ech schwammen um Weier, an ech hunn en orange Schniewel.|Ech hu Fiederen, an ech ka schwammen, goen a fléien.",
   zh:"我会嘎嘎叫。|我会游泳。|我有橙色的脚。|我在池塘里游泳，有一张扁扁的橙色嘴巴。|我有羽毛，会游泳，会走路，还会飞。"},
  {w:"frog", i:"#43A047|⬆️|🗣️", no:"duck,turtle,crocodile,snake", en:"I am green.|I can jump very far.|I say ribbit.|When I was little, I was a tadpole in the pond.|I catch flies with my long sticky tongue.",
   de:"Ich bin grün.|Ich springe sehr weit.|Ich mache quak.|Als ich klein war, war ich eine Kaulquappe im Teich.|Ich fange Fliegen mit meiner langen, klebrigen Zunge.",
   lb:"Ech si gréng.|Ech sprange ganz wäit.|Ech quaken.|Wéi ech kleng war, war ech e Kauzekapp am Weier.|Ech fänke Mécken mat menger laanger, pecheger Zong.",
   zh:"我是绿色的。|我跳得很远。|我会呱呱叫。|我小时候是池塘里的一只小蝌蚪。|我用又长又黏的舌头抓苍蝇。"},
  {w:"rabbit", i:"👂|🥕|⬆️", no:"kangaroo", en:"I have long ears.|I love carrots.|I hop.|I live in a hole under the ground, and I wiggle my nose.|My tail is small, round and soft like cotton.",
   de:"Ich habe lange Ohren.|Ich liebe Karotten.|Ich hoppele.|Ich wohne in einem Loch unter der Erde und wackle mit der Nase.|Mein Schwanz ist klein, rund und weich wie Watte.",
   lb:"Ech hu laang Oueren.|Ech iessen d'Muert gär.|Ech hoppelen.|Ech wunnen an engem Lach ënner der Äerd, an ech wibbele mat der Nues.|Mäi Schwanz ass kleng, ronn a mëll wéi Watt.",
   zh:"我有长长的耳朵。|我爱吃胡萝卜。|我蹦蹦跳跳。|我住在地下的洞里，鼻子总是动来动去。|我的尾巴小小的，圆圆的，像棉花一样软。"},
  {w:"monkey", i:"🍌|🌳|➰", no:"", en:"I love bananas.|I climb trees.|I have a long tail.|In the jungle, I jump from branch to branch.|I can hold things with my hands and with my feet.",
   de:"Ich liebe Bananen.|Ich klettere auf Bäume.|Ich habe einen langen Schwanz.|Im Dschungel springe ich von Ast zu Ast.|Ich kann Dinge mit den Händen und mit den Füßen halten.",
   lb:"Ech iessen d'Banann gär.|Ech kloteren op d'Beem.|Ech hunn e laange Schwanz.|Am Dschungel sprangen ech vun Aascht zu Aascht.|Ech ka Saache mat den Hänn a mat de Féiss halen.",
   zh:"我爱吃香蕉。|我会爬树。|我有一条长尾巴。|在丛林里，我从一根树枝跳到另一根树枝。|我的手和脚都能抓东西。"},
  {w:"elephant", i:"👃|#757575|👂", no:"", en:"I have a very long nose.|I am huge and grey.|I have huge ears.|I drink with my trunk, and I spray water everywhere.|I am the biggest animal that lives on land.",
   de:"Ich habe eine sehr lange Nase.|Ich bin riesig und grau.|Ich habe riesige Ohren.|Ich trinke mit meinem Rüssel und spritze überall Wasser herum.|Ich bin das größte Tier, das auf dem Land lebt.",
   lb:"Ech hunn eng ganz laang Nues.|Ech si riseg a gro.|Ech hu riseg Oueren.|Ech drénke mat mengem Rüssel, an ech sprëtze Waasser iwwerall hin.|Ech sinn dat gréisst Déier um Land.",
   zh:"我有一个很长很长的鼻子。|我特别大，是灰色的。|我有一对大大的耳朵。|我用长鼻子喝水，还会到处喷水。|我是陆地上最大的动物。"},
  {w:"mouse", i:"🤏|🧀|🗣️", no:"cat", en:"I am very small.|I love cheese.|I say squeak squeak.|I have a long thin tail, and I am afraid of cats.|I live in a little hole in the wall.",
   de:"Ich bin ganz klein.|Ich liebe Käse.|Ich mache piep, piep.|Ich habe einen langen, dünnen Schwanz und Angst vor Katzen.|Ich wohne in einem kleinen Loch in der Wand.",
   lb:"Ech si ganz kleng.|Ech iessen de Kéis gär.|Ech piipsen.|Ech hunn e laangen, dënne Schwanz, an ech hunn Angscht virun der Kaz.|Ech wunnen an engem klenge Lach an der Mauer.",
   zh:"我很小很小。|我爱吃奶酪。|我会吱吱叫。|我有一条细细长长的尾巴，我很怕猫。|我住在墙上的一个小洞里。"},
  {w:"chicken", i:"🥚|🗣️|🪶", no:"duck,bird,penguin,owl", en:"I lay eggs.|I say cluck cluck.|I have feathers.|I peck seeds from the ground with my beak.|My babies are little yellow chicks.",
   de:"Ich lege Eier.|Ich mache gack, gack.|Ich habe Federn.|Ich picke mit meinem Schnabel Körner vom Boden.|Meine Babys sind kleine gelbe Küken.",
   lb:"Ech leeën Eeër.|Ech gackeren.|Ech hu Fiederen.|Ech picke mat mengem Schniewel Käre vum Buedem.|Meng Puppelcher si kleng giel Jippelcher.",
   zh:"我会下蛋。|我会咯咯叫。|我身上有羽毛。|我用嘴在地上啄米粒。|我的宝宝毛茸茸的，是黄色的。"},
  {w:"lion", i:"👑|🗣️|💇", no:"tiger,cat", en:"I am the king of the animals.|I roar very loudly.|I have a big mane around my head.|I am a huge cat with golden fur.|I sleep in the sun, and I hunt with my family.",
   de:"Ich bin der König der Tiere.|Ich brülle ganz laut.|Ich habe eine große Mähne um den Kopf.|Ich bin eine riesige Katze mit goldenem Fell.|Ich schlafe in der Sonne und jage mit meiner Familie.",
   lb:"Ech sinn de Kinnek vun den Déieren.|Ech brëlle ganz haart.|Ech hunn en décke Kamp ëm de Kapp.|Ech sinn eng riseg Kaz mat engem gëllene Pelz.|Ech schlofen an der Sonn, an ech joe mat menger Famill.",
   zh:"我是动物之王。|我会大声吼叫。|我的头上围着一圈大鬃毛。|我是一只很大很大的猫，身上的毛是金色的。|我在太阳下睡觉，和家人一起去打猎。"},
  {w:"giraffe", i:"📏|🌳|#795548", no:"", en:"I have a very long neck.|I eat leaves from tall trees.|I have brown spots.|No other animal in the world is as tall as me.|My tongue is long and dark blue.",
   de:"Ich habe einen sehr langen Hals.|Ich fresse Blätter von hohen Bäumen.|Ich habe braune Flecken.|Kein Tier auf der Welt ist so groß wie ich.|Meine Zunge ist lang und dunkelblau.",
   lb:"Ech hunn e ganz laangen Hals.|Ech iesse Blieder uewen an de Beem.|Ech hu brong Flecken.|Keen Déier op der Welt ass esou héich wéi ech.|Meng Zong ass laang an donkelblo.",
   zh:"我的脖子很长很长。|我吃高高的树上的叶子。|我身上有棕色的斑点。|世界上没有别的动物比我更高。|我的舌头很长，是深蓝色的。"},
  {w:"snake", i:"🚫🦵|🗣️|📏", no:"fish,whale,dolphin", en:"I have no legs.|I hiss.|I am long.|I move without legs, and I stick out my tongue.|When I grow, I lose my old skin.",
   de:"Ich habe keine Beine.|Ich zische.|Ich bin lang.|Ich bewege mich ohne Beine und strecke die Zunge heraus.|Wenn ich wachse, verliere ich meine alte Haut.",
   lb:"Ech hu keng Been.|Ech zischen.|Ech si laang.|Ech beweege mech ouni Been, an ech strecken d'Zong eraus.|Wann ech wuessen, verléieren ech meng al Haut.",
   zh:"我没有腿。|我会发出嘶嘶声。|我长长的。|我没有腿也能爬，还会吐舌头。|我长大的时候，会把旧皮脱掉。"},
  {w:"penguin", i:"⚫⚪|🐦🚫|❄️", no:"cow,zebra,chicken,bird,duck", en:"I am black and white.|I am a bird, but I cannot fly.|I love the cold.|I live where it is very cold, and I swim very well.|I waddle in a funny way across the ice.",
   de:"Ich bin schwarz und weiß.|Ich bin ein Vogel, aber ich kann nicht fliegen.|Ich mag die Kälte.|Ich lebe, wo es sehr kalt ist, und schwimme sehr gut.|Ich watschle ganz lustig über das Eis.",
   lb:"Ech si schwaarz a wäiss.|Ech sinn e Vull, mee ech kann net fléien.|Ech hunn d'Keelt gär.|Ech liewen, wou et ganz kal ass, an ech schwamme ganz gutt.|Ech wackele ganz witzeg iwwer d'Äis.",
   zh:"我是黑白色的。|我是一种鸟，可是我不会飞。|我喜欢寒冷。|我住在很冷很冷的地方，游泳游得很好。|我在冰上走路摇摇摆摆的，特别好笑。"},
  {w:"owl", i:"🌙|🗣️|👀", no:"bird", en:"I fly at night.|I say hoot hoot.|I have huge round eyes.|I sleep all day, and I wake up when it gets dark.|I can turn my head almost all the way round.",
   de:"Ich fliege in der Nacht.|Ich mache schuhu.|Ich habe riesige, runde Augen.|Ich schlafe den ganzen Tag und wache auf, wenn es dunkel wird.|Ich kann meinen Kopf fast ganz herumdrehen.",
   lb:"Ech fléien an der Nuecht.|Ech maachen uhu.|Ech hu riseg ronn Aen.|Ech schlofen de ganzen Dag, an ech erwächen, wann et däischter gëtt.|Ech ka mäi Kapp bal ganz ronderëm dréinen.",
   zh:"我在晚上飞。|我会咕咕叫。|我有一双又大又圆的眼睛。|我白天睡觉，天黑了才醒来。|我的头几乎能转一整圈。"},
  {w:"octopus", i:"🌊|8️⃣|💦", no:"", en:"I live in the sea.|I have eight arms.|I squirt ink.|I live in the sea, and I have eight long arms.|I can change colour and hide between the stones.",
   de:"Ich lebe im Meer.|Ich habe acht Arme.|Ich spritze Tinte.|Ich lebe im Meer und habe acht lange Arme.|Ich kann meine Farbe ändern und mich zwischen Steinen verstecken.",
   lb:"Ech liewen am Mier.|Ech hunn aacht Äerm.|Ech sprëtzen Tënt.|Ech liewen am Mier, an ech hunn aacht laang Äerm.|Ech ka meng Faarf änneren, an ech verstoppe mech tëscht de Steng.",
   zh:"我住在大海里。|我有八条腿。|我会喷墨汁。|我住在大海里，有八条长长的腿。|我会变颜色，还会躲在石头中间。"},
  {w:"butterfly", i:"🎨|🌸|🐛", no:"bird,owl", en:"I have colourful wings.|I love flowers.|I was a caterpillar.|I fly from flower to flower in the garden.|When I was little, I was a hungry caterpillar.",
   de:"Ich habe bunte Flügel.|Ich liebe Blumen.|Ich war eine Raupe.|Ich fliege im Garten von Blume zu Blume.|Als ich klein war, war ich eine hungrige Raupe.",
   lb:"Ech hu ganz faarweg Flilleken.|Ech hunn d'Blumme gär.|Ech war eng Raup.|Ech fléie vu Blumm zu Blumm am Gaart.|Wéi ech kleng war, war ech eng hongereg Raup.",
   zh:"我有彩色的翅膀。|我喜欢花。|我以前是一条毛毛虫。|我在花园里从一朵花飞到另一朵花。|我小时候是一条饿坏了的毛毛虫。"},
  /* food */
  {w:"banana", i:"#FDD835|📏|🐵", no:"lemon,pineapple", en:"I am yellow.|I am long.|Monkeys love me.|Before you eat me, you peel off my yellow skin.|I grow in hot countries.",
   de:"Ich bin gelb.|Ich bin lang.|Affen lieben mich.|Bevor du mich isst, schälst du meine gelbe Schale ab.|Ich wachse in warmen Ländern.",
   lb:"Ech si giel.|Ech si laang.|D'Afen iesse mech gär.|Ier s de mech ëss, schiels de meng giel Schuel.|Ech wuessen a waarme Länner.",
   zh:"我是黄色的。|我长长的。|猴子最爱吃我。|吃我之前，要先剥掉黄色的皮。|我长在很热的地方。"},
  {w:"apple", i:"#E53935 #43A047|🌳|⭕", no:"tomato,cherries,pear,orange,peach,strawberry", en:"I am red or green.|I grow on a tree.|I am round and crunchy.|I am a crunchy fruit with little seeds inside.|In autumn I am ripe, and people make juice from me.",
   de:"Ich bin rot oder grün.|Ich wachse am Baum.|Ich bin rund und knackig.|Ich bin eine knackige Frucht mit kleinen Kernen innen drin.|Im Herbst bin ich reif, und man macht Saft aus mir.",
   lb:"Ech si rout oder gréng.|Ech wuessen um Bam.|Ech si ronn a knuspereg.|Ech sinn eng knuspereg Fruucht mat klenge Kären.|Am Hierscht sinn ech räif, an et gëtt Jus aus mir gemaach.",
   zh:"我是红色的，或者绿色的。|我长在树上。|我圆圆的，咬起来脆脆的。|我是一种脆脆的水果，里面有小小的籽。|秋天我就熟了，大家用我榨果汁。"},
  {w:"strawberry", i:"#E53935|🍬|🔍", no:"cherries,tomato,apple,watermelon", en:"I am red.|I am small and sweet.|My seeds are on the outside.|I am a red fruit with tiny seeds on my skin.|In summer, people eat me with whipped cream.",
   de:"Ich bin rot.|Ich bin klein und süß.|Meine Kerne sind außen.|Ich bin eine rote Frucht mit winzigen Kernen auf der Haut.|Im Sommer isst man mich gern mit Sahne.",
   lb:"Ech si rout.|Ech si kleng a séiss.|Meng Käre sinn dobaussen.|Ech sinn eng rout Fruucht mat klenge Kären op der Haut.|Am Summer ësst ee mech gär mat Klappschmant.",
   zh:"我是红色的。|我小小的，甜甜的。|我的籽长在外面。|我是红色的水果，皮上有很多小小的籽。|夏天，大家喜欢把我和奶油一起吃。"},
  {w:"watermelon", i:"#43A047|#E53935|🏋️", no:"apple", en:"I am green outside.|I am red inside.|I am huge and heavy.|I am huge and round, and I have black seeds inside.|I am full of water, perfect for a hot summer day.",
   de:"Außen bin ich grün.|Innen bin ich rot.|Ich bin riesig und schwer.|Ich bin riesig und rund, und innen habe ich schwarze Kerne.|Ich bin voller Wasser, genau richtig für einen heißen Sommertag.",
   lb:"Dobausse sinn ech gréng.|Dobanne sinn ech rout.|Ech si riseg a schwéier.|Ech si riseg a ronn, an dobannen hunn ech schwaarz Kären.|Ech si voller Waasser, genau richteg fir e waarme Summerdag.",
   zh:"我外面是绿色的。|我里面是红色的。|我又大又重。|我又大又圆，里面有黑色的籽。|我的水特别多，最适合炎热的夏天。"},
  {w:"bread", i:"🧑‍🍳|🌅|🔥", no:"cake,sandwich,pizza", en:"The baker makes me.|You eat me for breakfast.|I come out of a hot oven.|I am crispy outside and soft inside.|You can spread butter and jam on me.",
   de:"Der Bäcker macht mich.|Du isst mich zum Frühstück.|Ich komme aus dem heißen Ofen.|Außen bin ich knusprig und innen ganz weich.|Man kann Butter und Marmelade auf mich streichen.",
   lb:"De Bäcker mécht mech.|Du ëss mech zum Moiesiessen.|Ech kommen aus dem waarmen Uewen.|Dobausse sinn ech knuspereg an dobanne ganz mëll.|Du kanns Botter a Gebeess op mech schmieren.",
   zh:"我是烘焙师傅做的。|早饭的时候，你会吃我。|我是从热热的烤箱里出来的。|我外面脆脆的，里面软软的。|你可以在我上面抹黄油和果酱。"},
  {w:"cheese", i:"🐭|🥛|🕳️", no:"milk,pizza,ice cream", en:"Mice love me.|I am made from milk.|Sometimes I have holes.|I am yellow, and sometimes I have little holes.|You put me on pizza, and I melt in the oven.",
   de:"Mäuse lieben mich.|Ich werde aus Milch gemacht.|Manchmal habe ich Löcher.|Ich bin gelb und habe manchmal kleine Löcher.|Man legt mich auf die Pizza, und im Ofen schmelze ich.",
   lb:"D'Mais hu mech gär.|Ech gi mat Mëllech gemaach.|Heiansdo hunn ech Lächer.|Ech si giel, an heiansdo hunn ech kleng Lächer.|Ech kommen op d'Pizza, an am Uewe schmëlzen ech.",
   zh:"老鼠最爱吃我。|我是用牛奶做的。|我身上有时候有洞。|我是黄色的，有时候身上有小洞。|我放在披萨上，在烤箱里会化开。"},
  {w:"milk", i:"#FFFFFF|🐮|🥤", no:"cheese,ice cream", en:"I am white.|Cows give me.|You drink me.|In the morning, I go in your bowl with cereal.|I make your teeth and bones strong.",
   de:"Ich bin weiß.|Kühe geben mich.|Du trinkst mich.|Morgens komme ich mit Müsli in deine Schüssel.|Ich mache deine Zähne und Knochen stark.",
   lb:"Ech si wäiss.|D'Kéi gi mech.|Du drénks mech.|Moies kommen ech an deng Schossel mat Müsli.|Ech maachen deng Zänn an deng Schanke staark.",
   zh:"我是白色的。|我是奶牛给的。|你可以喝我。|早上，我和麦片一起倒进你的碗里。|我让你的牙齿和骨头更结实。"},
  {w:"egg", i:"🐔|#FDD835|💥", no:"chicken", en:"A hen lays me.|I am yellow inside.|I break easily.|A little chick can come out of me.|In the morning, you can boil me or fry me.",
   de:"Ein Huhn legt mich.|Innen bin ich gelb.|Ich gehe leicht kaputt.|Aus mir kann ein kleines Küken schlüpfen.|Morgens kannst du mich kochen oder braten.",
   lb:"D'Hong leet mech.|Dobanne sinn ech giel.|Ech gi liicht futti.|Aus mir kann e klengt Jippelche kommen.|Moies kanns de mech kachen oder broden.",
   zh:"母鸡生下了我。|我里面是黄色的。|我很容易碎。|一只小鸡可以从我里面钻出来。|早上，你可以把我煮一煮，或者煎一煎。"},
  {w:"cake", i:"🍬|🎉|🕯️", no:"bread,ice cream", en:"I am sweet.|You eat me on your birthday.|Candles stand on top of me.|I am made with eggs, flour, butter and sugar.|Everybody sings, and you blow out my candles.",
   de:"Ich bin süß.|Du isst mich an deinem Geburtstag.|Auf mir stehen Kerzen.|Man macht mich aus Eiern, Mehl, Butter und Zucker.|Alle singen, und du bläst meine Kerzen aus.",
   lb:"Ech si séiss.|Du ëss mech op dengem Gebuertsdag.|Op mir sti Käerzen.|Ech gi mat Eeër, Miel, Botter an Zocker gemaach.|Jidderee séngt, an du bléis meng Käerzen aus.",
   zh:"我甜甜的。|过生日的时候，你会吃我。|我上面插着蜡烛。|我是用鸡蛋、面粉、黄油和糖做的。|大家一起唱歌，你来吹灭我上面的蜡烛。"},
  {w:"carrot", i:"#FB8C00|🐰|🟫", no:"orange,snowman,rabbit", en:"I am orange.|Rabbits love me.|I grow in the ground.|I grow under the ground, and my leaves on top are green.|A snowman uses me as his nose.",
   de:"Ich bin orange.|Hasen lieben mich.|Ich wachse in der Erde.|Ich wachse unter der Erde, und oben habe ich grüne Blätter.|Ein Schneemann benutzt mich als Nase.",
   lb:"Ech sinn orange.|D'Kanéngercher iesse mech gär.|Ech wuessen an der Äerd.|Ech wuessen ënner der Äerd, an uewen hunn ech gréng Blieder.|De Schnéimännchen huet mech als Nues.",
   zh:"我是橙色的。|兔子最爱吃我。|我长在土里。|我长在土里，上面有绿色的叶子。|雪人用我当鼻子。"},
  {w:"pizza", i:"⭕|🧀|🔺", no:"cheese,cake,tomato,bread,sandwich", en:"I am round and flat.|I have cheese on top.|You cut me into triangles.|I have tomato sauce and cheese on top.|I come from Italy, and you may eat me with your hands.",
   de:"Ich bin rund und flach.|Oben auf mir ist Käse.|Man schneidet mich in Dreiecke.|Ich habe Tomatensoße und Käse obendrauf.|Ich komme aus Italien, und du darfst mich mit den Händen essen.",
   lb:"Ech si ronn a flaach.|Op mir ass Kéis.|Ech ginn an Dräiecker geschnidden.|Op mir sinn Tomatenzooss a Kéis.|Ech kommen aus Italien, an du däerfs mech mat den Hänn iessen.",
   zh:"我圆圆的，扁扁的。|我上面有奶酪。|你可以把我切成三角形。|我上面有番茄酱和奶酪。|我来自意大利，你可以用手拿着我吃。"},
  {w:"ice cream", i:"🥶|☀️|🍬", no:"snowman,cake,milk", en:"I am very cold.|I melt in the sun.|I am sweet.|On a hot summer day, you lick me before I melt.|I come in many flavours, like chocolate and vanilla.",
   de:"Ich bin ganz kalt.|In der Sonne schmelze ich.|Ich bin süß.|An heißen Sommertagen leckst du mich, bevor ich schmelze.|Mich gibt es in vielen Sorten, zum Beispiel Schokolade und Vanille.",
   lb:"Ech si ganz kal.|An der Sonn schmëlzen ech.|Ech si séiss.|Op engem waarme Summerdag lecks de mech, ier ech schmëlzen.|Mech gëtt et a villen Zorten, wéi Schockela a Vanill.",
   zh:"我冰冰凉凉的。|我在太阳下会化掉。|我甜甜的。|炎热的夏天，你要在我化掉之前把我舔完。|我有很多口味，比如巧克力味和香草味。"},
  {w:"lemon", i:"#FDD835|😖|🥤", no:"banana,orange,pineapple", en:"I am yellow.|I am very sour.|People squeeze juice out of me.|I am yellow and so sour that you pull a funny face.|My juice goes on fish and into tea.",
   de:"Ich bin gelb.|Ich bin sehr sauer.|Man presst Saft aus mir.|Ich bin gelb und so sauer, dass du eine lustige Grimasse ziehst.|Mein Saft kommt auf den Fisch und in den Tee.",
   lb:"Ech si giel.|Ech si ganz sauer.|Aus mir gëtt Jus gepresst.|Ech si giel an esou sauer, datt s de eng Grimass méchs.|Mäi Jus kënnt op de Fësch an an den Téi.",
   zh:"我是黄色的。|我非常酸。|大家用我榨汁。|我是黄色的，酸得让你做鬼脸。|我的汁可以挤在鱼上，也可以放进茶里。"},
  /* body */
  {w:"nose", i:"🙂|🌸|🤧", no:"face,mouth,ear", en:"I am in the middle of your face.|I smell the flowers.|I sneeze: atchoo!|I help you smell, and I run when you have a cold.|You blow me with a tissue.",
   de:"Ich bin mitten in deinem Gesicht.|Ich rieche die Blumen.|Ich niese: hatschi!|Mit mir riechst du, und wenn du erkältet bist, laufe ich.|Du putzt mich mit einem Taschentuch.",
   lb:"Ech sinn an der Mëtt vun dengem Gesiicht.|Ech richen d'Blummen.|Ech néitsen: hatschi!|Ech hëllefen dir ze richen, an ech lafen, wann s de de Schnapp hues.|Du botz mech mat engem Schnappech.",
   zh:"我在你脸的正中间。|我能闻到花香。|我会打喷嚏：阿嚏！|我帮你闻味道，你感冒的时候我会一直流水。|你会用纸巾擦我。"},
  {w:"ear", i:"🔊|2️⃣|🎵", no:"eyes,hand,foot,leg,arm,mouth,bird", en:"I help you hear.|You have two of me.|I love music.|With me, you hear music, birds and voices.|There is one of me on each side of your head.",
   de:"Ich helfe dir beim Hören.|Du hast zwei von mir.|Ich liebe Musik.|Mit mir hörst du Musik, Vögel und Stimmen.|Auf jeder Seite von deinem Kopf ist eins von mir.",
   lb:"Ech hëllefen dir ze héieren.|Du hues zwee vu mir.|Ech hunn d'Musek gär.|Mat mir héiers de Musek, Vullen a Stëmmen.|Op all Säit vun dengem Kapp ass eent vu mir.",
   zh:"我帮你听声音。|你有两只我，一边一只。|我喜欢听音乐。|有了我，你能听到音乐、鸟叫和说话声。|你的头两边各有一只我。"},
  {w:"tooth", i:"#FFFFFF|🪥|🍎", no:"hair", en:"I am white.|You brush me.|I help you bite.|You brush me every morning and every evening.|When I fall out, a new one grows in my place.",
   de:"Ich bin weiß.|Du putzt mich.|Ich helfe dir beim Beißen.|Du putzt mich jeden Morgen und jeden Abend.|Wenn ich ausfalle, wächst ein neuer an meiner Stelle.",
   lb:"Ech si wäiss.|Du botz mech.|Ech hëllefen dir beim Bäissen.|Du botz mech all Moien an all Owend.|Wann ech erausfalen, wiisst en neien op menger Plaz.",
   zh:"我是白色的。|你每天刷我。|我帮你咬东西。|你每天早上和晚上都要刷我。|我掉了以后，会长出一颗新的。"},
  {w:"hand", i:"👋|👏|5️⃣", no:"foot,finger,arm", en:"I wave goodbye.|I clap.|I have five fingers.|With me, you write, draw and hold things.|I am at the end of your arm.",
   de:"Ich winke tschüss.|Ich klatsche.|Ich habe fünf Finger.|Mit mir schreibst du, malst du und hältst du Dinge.|Ich bin am Ende von deinem Arm.",
   lb:"Ech wénken Äddi.|Ech klappen.|Ech hu fënnef Fangeren.|Mat mir schreifs de, mols de an häls de Saachen.|Ech sinn um Enn vun dengem Aarm.",
   zh:"我会挥一挥说再见。|我会拍巴掌。|我有五根指头。|你用我写字、画画、拿东西。|我在你胳膊的最末端。"},
  {w:"foot", i:"🦵|👟|5️⃣", no:"leg,hand,shoes,socks,boots", en:"I am at the bottom of your leg.|I wear a shoe.|I have five toes.|You stand and walk on me all day.|You put a sock and a shoe on me.",
   de:"Ich bin unten an deinem Bein.|Ich trage einen Schuh.|Ich habe fünf Zehen.|Du stehst und läufst den ganzen Tag auf mir.|Du ziehst mir eine Socke und einen Schuh an.",
   lb:"Ech sinn ënnen un dengem Been.|Ech droen e Schong.|Ech hu fënnef Zéiwen.|Du stees a gees de ganzen Dag op mir.|Du dees mir eng Strëmp an e Schong un.",
   zh:"我在你腿的最下面。|我穿鞋子。|我有五个小趾头。|你整天用我站着、走路。|你给我穿上袜子和鞋子。"},
  {w:"tongue", i:"#F48FB1|👄|🍭", no:"mouth,tooth,ice cream", en:"I am pink.|I live in your mouth.|I taste your food.|With me, you taste sweet and sour things.|You stick me out to lick an ice cream.",
   de:"Ich bin rosa.|Ich wohne in deinem Mund.|Ich schmecke dein Essen.|Mit mir schmeckst du Süßes und Saures.|Du streckst mich heraus, um an einem Eis zu lecken.",
   lb:"Ech si rosa.|Ech wunnen an dengem Mond.|Ech schmaachen däin Iessen.|Mat mir schmaachs de séiss a sauer Saachen.|Du strecks mech eraus, fir eng Glace ze lecken.",
   zh:"我是粉红色的。|我住在你的嘴巴里。|我帮你尝味道。|有了我，你能尝出甜的和酸的。|你伸出我来舔冰淇淋。"},
  /* things */
  {w:"ball", i:"⭕|🦶|⬆️", no:"orange,apple,pizza,watermelon", en:"I am round.|You kick me.|I bounce.|You kick me into the goal.|When you throw me, I bounce up and down.",
   de:"Ich bin rund.|Du schießt mich mit dem Fuß.|Ich hüpfe hoch.|Du schießt mich ins Tor.|Wenn du mich wirfst, springe ich auf und ab.",
   lb:"Ech si ronn.|Du schéiss mech mam Fouss.|Ech sprangen.|Du schéiss mech an de Gol.|Wann s de mech geheis, sprangen ech op an of.",
   zh:"我圆圆的。|你用脚踢我。|我会弹起来。|你把我踢进球门。|你把我扔出去，我会上下弹跳。"},
  {w:"car", i:"4️⃣|🗣️|🛣️", no:"bus,train,bike", en:"I have four wheels.|I go vroom vroom.|I drive on the road.|You sit inside me and fasten your seat belt.|I need petrol or electricity to go.",
   de:"Ich habe vier Räder.|Ich mache brumm, brumm.|Ich fahre auf der Straße.|Du sitzt in mir und schnallst dich an.|Ich brauche Benzin oder Strom, um zu fahren.",
   lb:"Ech hu véier Rieder.|Ech maache brumm brumm.|Ech fueren op der Strooss.|Du sëtz a mir a maachs de Sécherheetsgurt zou.|Ech brauch Bensinn oder Stroum, fir ze fueren.",
   zh:"我有四个轮子。|我会嘀嘀叫。|我在马路上跑。|你坐在我里面，要系好安全带。|我要加油或者充电才能跑。"},
  {w:"boat", i:"🌊|💨|⚓", no:"duck,fish,whale,dolphin", en:"I float on the water.|The wind pushes me.|I have an anchor.|The wind blows my sail across the sea.|Sailors live and work on me.",
   de:"Ich schwimme auf dem Wasser.|Der Wind schiebt mich an.|Ich habe einen Anker.|Der Wind bläst mein Segel über das Meer.|Matrosen leben und arbeiten auf mir.",
   lb:"Ech schwammen um Waasser.|De Wand dréckt mech.|Ech hunn en Anker.|De Wand bléist mäi Seegel iwwer d'Mier.|Matrouse liewen a schaffen op mir.",
   zh:"我漂在水面上。|风推着我走。|我有一个锚。|风吹着我的帆，带我穿过大海。|水手们在我上面生活和工作。"},
  {w:"plane", i:"☁️|🌍|👨‍👩‍👧", no:"bird,helicopter,rocket,butterfly,owl", en:"I fly in the sky.|I take you to faraway countries.|I carry lots of people.|I carry many people high above the clouds.|I take off and land at the airport.",
   de:"Ich fliege am Himmel.|Ich bringe dich in ferne Länder.|Ich trage viele Menschen.|Ich trage viele Menschen hoch über die Wolken.|Ich starte und lande am Flughafen.",
   lb:"Ech fléien um Himmel.|Ech bréngen dech a wäit Länner.|Ech droe vill Leit.|Ech droe vill Leit héich iwwer d'Wolleken.|Ech starten a landen um Fluchhafen.",
   zh:"我在天上飞。|我带你去很远的国家。|我能坐很多人。|我载着很多人，飞到云的上面。|我在机场起飞和降落。"},
  {w:"train", i:"🛤️|🗣️|🚉", no:"bus,car", en:"I run on rails.|I go choo choo.|I stop at the station.|You wait for me at the station with your ticket.|I am very long, and I have many carriages.",
   de:"Ich fahre auf Schienen.|Ich mache tschu, tschu.|Ich halte am Bahnhof.|Du wartest mit deiner Fahrkarte am Bahnhof auf mich.|Ich bin sehr lang und habe viele Wagen.",
   lb:"Ech fueren op Schinnen.|Ech maachen tschu tschu.|Ech halen op der Gare.|Du waarts mat dengem Billjee op der Gare op mech.|Ech si ganz laang, an ech hu vill Waggonen.",
   zh:"我在铁轨上跑。|我会呜呜叫。|我在车站停下来。|你拿着车票在站台上等我。|我很长很长，有很多节车厢。"},
  {w:"book", i:"📄|👀|💬", no:"", en:"I have pages.|You can read me.|I tell stories.|I have many pages full of words and pictures.|At bedtime, Mum or Dad reads me to you.",
   de:"Ich habe Seiten.|Du kannst mich lesen.|Ich erzähle Geschichten.|Ich habe viele Seiten voller Wörter und Bilder.|Vor dem Schlafen liest Mama oder Papa dir aus mir vor.",
   lb:"Ech hu Säiten.|Du kanns mech liesen.|Ech erziele Geschichten.|Ech hu vill Säite voller Wierder a Biller.|Owes virum Schlofe liest de Papp oder d'Mamm dir aus mir vir.",
   zh:"我有很多页。|你可以读我。|我会讲故事。|我有很多页，上面有字和图画。|睡觉前，爸爸妈妈会给你读我。"},
  {w:"tree", i:"⬆️|🍃|🐦", no:"flower", en:"I am very tall.|I have leaves.|Birds live in me.|I have a trunk, branches and green leaves.|In autumn, all my leaves fall down.",
   de:"Ich bin sehr hoch.|Ich habe Blätter.|Vögel wohnen in mir.|Ich habe einen Stamm, Äste und grüne Blätter.|Im Herbst fallen alle meine Blätter herunter.",
   lb:"Ech si ganz héich.|Ech hu Blieder.|D'Vulle wunnen a mir.|Ech hunn e Stamm, Äscht a gréng Blieder.|Am Hierscht falen all meng Blieder erof.",
   zh:"我很高很高。|我有叶子。|小鸟住在我身上。|我有粗粗的身体、很多枝条和绿色的叶子。|秋天，我的叶子都掉下来了。"},
  {w:"sun", i:"#FDD835|🔥|🕶️", no:"star,moon,lemon,banana", en:"I am yellow.|I am very hot.|I am very bright.|I shine in the sky all day and keep you warm.|In the evening I go down, and then the moon comes out.",
   de:"Ich bin gelb.|Ich bin sehr heiß.|Ich bin sehr hell.|Ich scheine den ganzen Tag am Himmel und wärme dich.|Am Abend gehe ich unter, und dann kommt der Mond.",
   lb:"Ech si giel.|Ech si ganz waarm.|Ech si ganz hell.|Ech schéngen de ganzen Dag um Himmel, an ech maachen dech waarm.|Owes ginn ech ënner, an da kënnt de Mound.",
   zh:"我是黄色的。|我非常热。|我非常亮。|我整天在天上照着，让你暖暖和和的。|晚上我落下去，然后月亮就出来了。"},
  {w:"moon", i:"🌃|🍌|🧑‍🚀", no:"star,sun,banana,owl,rocket", en:"I shine at night.|Sometimes I look like a banana.|Astronauts walked on me.|At night I shine in the sky, and sometimes I am completely round.|Astronauts came to visit me in a rocket.",
   de:"Ich leuchte in der Nacht.|Manchmal sehe ich aus wie eine Banane.|Astronauten sind auf mir gelaufen.|Nachts leuchte ich am Himmel, und manchmal bin ich ganz rund.|Astronauten haben mich mit einer Rakete besucht.",
   lb:"Ech liichten an der Nuecht.|Heiansdo gesinn ech aus wéi eng Banann.|Astronaute sinn op mir gaangen.|Nuets liichten ech um Himmel, an heiansdo sinn ech ganz ronn.|Astronauten hu mech an enger Rakéit besicht.",
   zh:"我在晚上发光。|有时候我看起来像一根香蕉。|宇航员在我上面走过。|晚上我挂在天上，有时候圆圆的。|宇航员坐着火箭来看过我。"},
  {w:"umbrella", i:"🌧️|💧|🙆", no:"coat,boots,cloud,hat", en:"You open me when it rains.|I keep you dry.|You hold me over your head.|When the wind blows hard, I can turn inside out.|I have a long handle, and when the rain stops, you close me.",
   de:"Wenn es regnet, spannst du mich auf.|Ich halte dich trocken.|Du hältst mich über deinen Kopf.|Wenn der Wind stark bläst, kann ich umklappen.|Ich habe einen langen Griff, und wenn der Regen aufhört, klappst du mich zu.",
   lb:"Wann et reent, maachs de mech op.|Ech halen dech dréchen.|Du häls mech iwwer de Kapp.|Wann de Wand staark bléist, kann ech ëmklappen.|Ech hunn e laange Grëff, a wann de Reen ophält, maachs de mech zou.",
   zh:"下雨的时候，你把我打开。|我让你不被淋湿。|你把我举在头顶上。|风太大的时候，我会被吹得翻过来。|我有一个长长的把手，雨停了，你就把我收起来。"},
  {w:"rainbow", i:"🎨|🌧️|☀️", no:"sun,cloud,butterfly,umbrella", en:"I have many colours.|I come after the rain.|I need the sun.|I appear in the sky when the sun shines through the rain.|I have seven colours, from red to purple.",
   de:"Ich habe viele Farben.|Ich komme nach dem Regen.|Ich brauche die Sonne.|Ich erscheine am Himmel, wenn die Sonne durch den Regen scheint.|Ich habe sieben Farben, von Rot bis Lila.",
   lb:"Ech hu vill Faarwen.|Ech kommen nom Reen.|Ech brauch d'Sonn.|Ech erschéngen um Himmel, wann d'Sonn duerch de Ree schéngt.|Ech hu siwe Faarwen, vu rout bis mof.",
   zh:"我有很多颜色。|我在下雨以后出现。|我需要太阳。|太阳照着雨滴的时候，我就出现在天上。|我有七种颜色，从红色到紫色。"},
  {w:"rocket", i:"🌌|💨|🔥", no:"plane,helicopter,star,moon,astronaut", en:"I fly into space.|I am very fast.|Fire comes out of my bottom!|Astronauts sit inside me and fly to the moon.|Three, two, one... I blast off with a huge roar!",
   de:"Ich fliege ins Weltall.|Ich bin sehr schnell.|Aus meinem Po kommt Feuer!|Astronauten sitzen in mir und fliegen zum Mond.|Drei, zwei, eins ... ich starte mit lautem Donnern!",
   lb:"Ech fléien an de Weltall.|Ech si ganz séier.|Aus mengem Pupes kënnt Feier!|Astronaute sëtzen a mir a fléien op de Mound.|Dräi, zwee, eent ... an ech fléie fort mat engem décke Kaméidi!",
   zh:"我飞向太空。|我非常快。|我的屁股会喷火！|宇航员坐在我里面，飞向月亮。|三、二、一……我轰的一声飞上天！"},
  {w:"snowman", i:"❄️|🥕|☀️", no:"ice cream,carrot", en:"I am made of snow.|My nose is a carrot.|I melt in the sun.|Children build me in the garden in winter.|I have a carrot nose and buttons made of stones.",
   de:"Ich bin aus Schnee.|Meine Nase ist eine Karotte.|In der Sonne schmelze ich.|Kinder bauen mich im Winter im Garten.|Ich habe eine Karottennase und Knöpfe aus Steinen.",
   lb:"Ech sinn aus Schnéi.|Meng Nues ass eng Muert.|Wann d'Sonn schéngt, schmëlzen ech.|D'Kanner baue mech am Wanter am Gaart.|Ech hunn eng Nues aus enger Muert a Knäpp aus Steng.",
   zh:"我是用雪做的。|我的鼻子是一根胡萝卜。|太阳出来，我就会化掉。|冬天，小朋友在院子里把我堆起来。|我有胡萝卜鼻子，还有石头做的扣子。"},
  /* clothes */
  {w:"hat", i:"🙆|☀️|🪄", no:"cap,hair,rabbit", en:"You wear me on your head.|I keep the sun off your face.|A magician needs me.|A magician pulls a rabbit out of me: abracadabra!|You put me on before you go out in the sun.",
   de:"Du trägst mich auf dem Kopf.|Ich schütze dein Gesicht vor der Sonne.|Ein Zauberer braucht mich.|Ein Zauberer zieht ein Kaninchen aus mir: Abrakadabra!|Du setzt mich auf, bevor du in die Sonne gehst.",
   lb:"Du dréis mech um Kapp.|Ech schützen däi Gesiicht vun der Sonn.|En Zauberer brauch mech.|En Zauberer zitt eng Kanéngchen aus mir: Abrakadabra!|Du sets mech op, ier s de an d'Sonn gees.",
   zh:"你把我戴在头上。|我帮你的脸挡住太阳。|魔术师需要我。|魔术师能从我里面变出一只兔子：变变变！|出门晒太阳之前，你要把我戴上。"},
  {w:"scarf", i:"❄️|📏|🧶", no:"gloves,coat,hat", en:"I keep your neck warm.|I am long and soft.|Grandma knits me with wool.|You wrap me around your neck when it is cold.|I am long and woolly, and sometimes I have stripes.",
   de:"Ich halte deinen Hals warm.|Ich bin lang und weich.|Oma strickt mich aus Wolle.|Du wickelst mich um den Hals, wenn es kalt ist.|Ich bin lang und aus Wolle, und manchmal habe ich Streifen.",
   lb:"Ech halen däin Hals waarm.|Ech si laang a mëll.|D'Bomi stréckt mech aus Woll.|Du wéckels mech ëm den Hals, wann et kal ass.|Ech si laang a vu Woll, an heiansdo hunn ech Sträifen.",
   zh:"我让你的脖子暖暖的。|我长长的，软软的。|奶奶用毛线把我织出来。|天冷的时候，你把我绕在脖子上。|我是毛线织的，长长的，有时候还有条纹。"},
  {w:"coat", i:"❄️|🔘|🚪", no:"scarf,dress,T-shirt,umbrella,gloves", en:"I keep you warm.|I have buttons.|You put me on to go outside.|When it is cold, you wear me over your clothes.|I have long sleeves, pockets and buttons.",
   de:"Ich halte dich warm.|Ich habe Knöpfe.|Du ziehst mich an, wenn du nach draußen gehst.|Wenn es kalt ist, ziehst du mich über deine Kleider.|Ich habe lange Ärmel, Taschen und Knöpfe.",
   lb:"Ech halen dech waarm.|Ech hu Knäpp.|Du dees mech un, wann s de erausgees.|Wann et kal ass, dees de mech iwwer deng Kleeder un.|Ech hu laang Äerm, Täschen a Knäpp.",
   zh:"我让你暖暖和和的。|我身上有扣子。|你出门的时候穿上我。|天冷的时候，你把我穿在衣服外面。|我有长长的袖子、口袋和扣子。"},
  /* jobs */
  {w:"doctor", who:1, i:"🤒|🏥|🩺", no:"", en:"I help sick people.|I work in a hospital.|I listen to your heart.|When you are ill, I look in your mouth and in your ears.|I give you medicine so that you get well again.",
   de:"Ich helfe kranken Menschen.|Ich arbeite im Krankenhaus.|Ich höre dein Herz ab.|Wenn du krank bist, schaue ich in deinen Mund und in deine Ohren.|Ich gebe dir Medizin, damit du wieder gesund wirst.",
   lb:"Ech hëllefe kranke Leit.|Ech schaffen an engem Spidol.|Ech lauschteren, wéi däin Häerz klappt.|Wann s de krank bass, kucken ech an däi Mond an an deng Oueren.|Ech ginn dir Medikamenter, fir datt s de erëm gesond gëss.",
   zh:"我帮助生病的人。|我在医院工作。|我听你的心跳。|你生病的时候，我会看看你的嘴巴和耳朵。|我给你开药，让你快点好起来。"},
  {w:"teacher", who:1, i:"🏫|📚|✍️", no:"", en:"I work at a school.|I help children learn.|I write on the board.|I teach children to read, write and count.|I say: good morning, children! Open your books!",
   de:"Ich arbeite in der Schule.|Ich helfe Kindern beim Lernen.|Ich schreibe an die Tafel.|Ich bringe Kindern Lesen, Schreiben und Rechnen bei.|Ich sage: Guten Morgen, Kinder! Macht eure Bücher auf!",
   lb:"Ech schaffen an der Schoul.|Ech hëllefen de Kanner beim Léieren.|Ech schreiwen op d'Tafel.|Ech bréngen de Kanner Liesen, Schreiwen a Rechne bäi.|Ech soen: Gudde Moien, Kanner! Maacht är Bicher op!",
   zh:"我在学校工作。|我帮助小朋友学习。|我在黑板上写字。|我教小朋友读书、写字和算数。|我会说：同学们早上好！请打开书！"},
  {w:"farmer", who:1, i:"🌾|🚜|⏰", no:"cow,pig,chicken,horse,sheep,duck", en:"I work on a farm.|I drive a tractor.|I get up very early.|I look after cows, pigs and chickens.|Wheat and vegetables grow in my fields.",
   de:"Ich arbeite auf dem Hof.|Ich fahre Traktor.|Ich stehe ganz früh auf.|Ich kümmere mich um Kühe, Schweine und Hühner.|Auf meinen Feldern wachsen Weizen und Gemüse.",
   lb:"Ech schaffen um Haff.|Ech fuere mam Trakter.|Ech sti ganz fréi op.|Ech këmmere mech ëm d'Kéi, d'Schwäin an d'Hénger.|Op menge Felder wuesse Weess a Geméis.",
   zh:"我在农场工作。|我开拖拉机。|我每天很早就起床。|我照顾奶牛、猪和鸡。|我的田里长着小麦和蔬菜。"},
  {w:"firefighter", who:1, i:"🔥|🚒|💦", no:"police officer", en:"I put out fires.|I drive a big red truck.|I spray water with a hose.|I climb up tall ladders to rescue people.|When something is on fire, I come with my siren: nee naw!",
   de:"Ich lösche Feuer.|Ich fahre ein großes rotes Auto.|Ich spritze Wasser mit einem Schlauch.|Ich klettere auf hohe Leitern und rette Menschen.|Wenn es brennt, komme ich mit Blaulicht und Sirene: tatütata!",
   lb:"Ech läschen d'Feier.|Ech fuere mat engem grousse roude Camion.|Ech sprëtze Waasser mat engem Schlauch.|Ech kloteren op héich Leederen, fir Leit ze retten.|Wann et brennt, kommen ech mat der Sireen: tatütata!",
   zh:"我会灭火。|我开一辆红色的大车。|我用水管喷水。|我爬上高高的梯子去救人。|哪里着火了，我就鸣着警笛赶过去：嘀嘟嘀嘟！"},
  {w:"pilot", who:1, i:"✈️|☁️|🧢", no:"astronaut", en:"I fly a plane.|I work high up in the sky.|I wear a uniform and a cap.|I sit at the front of the plane and fly people around the world.|I say: seat belts on, off we go!",
   de:"Ich fliege ein Flugzeug.|Ich arbeite hoch oben am Himmel.|Ich trage eine Uniform und eine Mütze.|Ich sitze vorne im Flugzeug und fliege Menschen um die Welt.|Ich sage: Anschnallen, es geht los!",
   lb:"Ech steieren e Fliger.|Ech schaffen héich um Himmel.|Ech droen eng Uniform an eng Kap.|Ech sëtze vir am Fliger a fléien d'Leit ronderëm d'Welt.|Ech soen: Gurten zou, et geet lass!",
   zh:"我开飞机。|我在高高的天上工作。|我穿制服，戴帽子。|我坐在飞机的最前面，带大家飞遍全世界。|我会说：系好安全带，我们出发啦！"},
  {w:"astronaut", who:1, i:"🌌|🚀|🌙", no:"pilot", en:"I go to space.|I fly in a rocket.|I have walked on the moon.|I float in space in a thick white suit with a helmet.|I travel in a rocket, and I have already been to the moon.",
   de:"Ich fliege ins Weltall.|Ich fliege mit einer Rakete.|Ich bin schon auf dem Mond gelaufen.|Ich schwebe im Weltall, in einem dicken weißen Anzug mit Helm.|Ich reise mit einer Rakete und war schon auf dem Mond.",
   lb:"Ech fléien an de Weltall.|Ech fléie mat enger Rakéit.|Ech sinn um Mound gaangen.|Ech schwiewen am Weltall an engem décke wäisse Kostüm mat Helm.|Ech reese mat enger Rakéit, an ech war schonn um Mound.",
   zh:"我去太空。|我坐火箭飞行。|我在月亮上走过路。|我穿着厚厚的白衣服，戴着头盔，在太空里飘来飘去。|我坐火箭去旅行，还去过月亮。"}
];
