/* L'Île aux Mots : contenu du jeu « phrases » (Word Parade), dans les quatre langues apprises.
   Une phrase par ligne, avec l'ordre des mots propre à chaque langue (verbe en deuxième position en allemand et en luxembourgeois).
   Mots séparés par des espaces, en chinois aussi (découpe en mots) ; "_" colle un mot en plusieurs morceaux (next_to, ice_cream).
   e : image (emoji séparés par des espaces, le premier joue la phrase) ; o : placement de l'image (on, under, next, in, over, front, between) ;
   a : animation ; l : 1 (trois mots), 2 (adjectifs), 3 (prépositions) ; x : le mot en trop du niveau 4, en|de|lb|zh.
   Luxembourgeois vérifié sur lod.lu, règle de l'Eifel comprise (Ech iesse Brout, Kazen drénke Mëllech, e grousse Stär). */
const phrasesData = {
  title: {en: "Word Parade", de: "Wörterparade", lb: "Wierderparad", zh: "词语排排队"},
  sub: {en: "Build the sentence!", de: "Bau den Satz!", lb: "Bau de Saz!", zh: "把句子排好！"},
  txt: {
    en: {listen: "Listen and build the sentence!", look: "Look! Build the sentence.", extra: "One word is extra!", again: "Again",
      praise: ["Great sentence!", "Well done!", "Super!", "Yes!", "Perfect!"], oops: "Oops!", sneeze: "Achoo!", burp: "Burp!"},
    de: {listen: "Hör zu und bau den Satz!", look: "Schau! Bau den Satz.", extra: "Ein Wort ist zu viel!", again: "Nochmal",
      praise: ["Toller Satz!", "Super!", "Richtig!", "Prima!", "Sehr gut!"], oops: "Hoppla!", sneeze: "Hatschi!", burp: "Rülps!"},
    lb: {listen: "Lauschter a bau de Saz!", look: "Kuck! Bau de Saz.", extra: "Ee Wuert ass ze vill!", again: "Nach eng Kéier",
      praise: ["Super!", "Bravo!", "Richteg!", "Flott!", "Ganz gutt!"], oops: "Hoppla!", sneeze: "🤧", burp: "💨"},
    zh: {listen: "听一听，把句子排好！", look: "看图，把句子排好！", extra: "有一个词是多余的！", again: "再听一次",
      praise: ["太棒了！", "真棒！", "对了！", "好厉害！", "句子排好了！"], oops: "哎呀！", sneeze: "阿嚏！", burp: "嗝！"}
  },
  // pictures on the word tags, for the one who cannot read yet (the lexicon adds its own nouns)
  pics: [
    "🙋 I ich ech 我", "👫 we wir mir 我们", "👧 she sie si 她", "1️⃣ a ein einen eine e eng 一个 一辆 一颗 一只 一顶", "👈 my mein mäin 我的",
    "🏃 runs rennt leeft 跑", "😴 sleeps schläft schléift 睡觉 sleeping schlafen schlofen", "🦘 jumps springt spréngt 跳",
    "🎤 sings singt séngt 唱歌", "🏊 swim swims swimming schwimmt schwimmen schwëmmt schwammen 游泳 游", "📢 roars brüllt brëllt 吼叫 叫",
    "🍽️ eat eats esse frisst fressen iesse frësst friesse 吃", "🥤 drink trinke trinken drénke 喝", "💃 dance tanzen danzen 跳舞",
    "🤝 together zusammen zesummen 一起", "🤸 play spielen spille 玩", "❤️ love liebe gär 喜欢", "🗯️ barks bellt billt 汪汪",
    "💪 can kann ka können kënne 会", "✈️ fly fliegen fléien 飞", "⬇️ lay legen leeën under unter ënner 下 下面",
    "⬆️ on auf op um 上 上面", "👀 see sehe gesinn 看见", "🤲 have has habe hat hunn huet 有",
    "😀 happy glücklich frou 开心", "😂 funny lustig witzeg 好玩", "😢 sad traurig traureg 难过",
    "🏔️ big groß großen großer grouss grousse 大", "🤏 small klein kleinen kleiner kleng klenge 小",
    "📏 tall long lang laang 高 长", "✂️ short kurz kuerz 短 矮", "⚡ fast schnell séier 快", "🐌 slow langsam lues 慢",
    "🔥 hot heiß waarm 热", "❄️ cold kalt kal 凉 冷", "💩 dirty schmutzig dreckeg 脏", "🧼 clean sauber propper 干净",
    "🔴 red rot rotes roter roten rote rout rouden roude 红色的", "🔵 blue blau blaue blaues blauen blo bloen 蓝色的",
    "🟢 green grünen gréng grénge 绿色的", "🟡 yellow gelb giel 黄色的", "⚫ black schwarz schwaarz 黑色的",
    "⚪ white weiß wäiss 白色的", "💗 pink rosa 粉色的", "2️⃣ two zwei zwou 两只", "3️⃣ three drei dräi 三只",
    "🐶 dogs 小狗", "🐻 Bier 小熊", "🐦 birds Vögel Vullen Vulle 小鸟", "🐟 小鱼", "🐮 cows Kühe Kéi", "🐵 monkeys Affen Afen Afe",
    "🍌 bananas Bananen Banannen", "🐔 hens Hühner Hénger 母鸡", "🥚 eggs Eier Eeër 蛋", "🐰 rabbits Kanéngercher",
    "🥕 carrots Karotten Muerten", "🌱 grass Gras 草", "🐱 cats Katzen Kazen 小猫", "🐷 小猪", "🎈 balloon Ballon 气球",
    "🧢 cap Kappe Kap 帽子", "🚕 taxi 出租车", "🛏️ bed Bett 床", "🪑 chair Stuhl Stull 椅子", "📦 box Kiste Këscht 箱子",
    "🌊 water Wasser Waasser 水 sea Meer Mier 海 pond Teich Weier 池塘", "🍽️ plate Teller 盘子", "🛁 bath Badewanne Bidden 浴缸", "🧊 ice Äis 冰"
  ],
  items: [
    // level 1: three words
    {l: 1, e: "🐶", a: "run", en: "The dog runs.", de: "Der Hund rennt.", lb: "Den Hond leeft.", zh: "小狗 在 跑。"},
    {l: 1, e: "🐻", a: "sleep", en: "The bear sleeps.", de: "Der Bär schläft.", lb: "De Bier schléift.", zh: "小熊 在 睡觉。"},
    {l: 1, e: "🐸", a: "hop", en: "The frog jumps.", de: "Der Frosch springt.", lb: "De Fräsch spréngt.", zh: "青蛙 在 跳。"},
    {l: 1, e: "🐦", a: "sing", en: "The bird sings.", de: "Der Vogel singt.", lb: "De Vull séngt.", zh: "小鸟 在 唱歌。"},
    {l: 1, e: "🐟", a: "swim", en: "The fish swims.", de: "Der Fisch schwimmt.", lb: "De Fësch schwëmmt.", zh: "小鱼 在 游泳。"},
    {l: 1, e: "🦁", a: "roar", en: "The lion roars.", de: "Der Löwe brüllt.", lb: "De Léiw brëllt.", zh: "狮子 在 吼叫。"},
    {l: 1, e: "🐶", a: "bark", en: "The dog barks.", de: "Der Hund bellt.", lb: "Den Hond billt.", zh: "小狗 汪汪 叫。"},
    {l: 1, e: "🧒 🍞", a: "eat", en: "I eat bread.", de: "Ich esse Brot.", lb: "Ech iesse Brout.", zh: "我 吃 面包。"},
    {l: 1, e: "🧒 🥛", a: "drink", en: "I drink milk.", de: "Ich trinke Milch.", lb: "Ech drénke Mëllech.", zh: "我 喝 牛奶。"},
    {l: 1, e: "🐱 🥛", a: "drink", en: "Cats drink milk.", de: "Katzen trinken Milch.", lb: "Kazen drénke Mëllech.", zh: "小猫 喝 牛奶。"},
    {l: 1, e: "🐮 🌱", a: "eat", en: "The cow eats grass.", de: "Die Kuh frisst Gras.", lb: "D'Kou frësst Gras.", zh: "奶牛 吃 草。"},
    {l: 1, e: "🐵 🍌", a: "eat", en: "Monkeys eat bananas.", de: "Affen fressen Bananen.", lb: "Afe friesse Banannen.", zh: "猴子 吃 香蕉。"},
    {l: 1, e: "🐰 🥕", a: "eat", en: "Rabbits eat carrots.", de: "Kaninchen fressen Karotten.", lb: "Kanéngercher friesse Muerten.", zh: "兔子 吃 胡萝卜。"},
    {l: 1, e: "🐔", a: "lay", en: "Hens lay eggs.", de: "Hühner legen Eier.", lb: "Hénger leeën Eeër.", zh: "母鸡 下 蛋。"},
    {l: 1, e: "⚽ 👫", a: "roll", en: "We play ball.", de: "Wir spielen Ball.", lb: "Mir spille Ball.", zh: "我们 玩 球。"},
    {l: 1, e: "💃 🕺", a: "dance", en: "We dance together.", de: "Wir tanzen zusammen.", lb: "Mir danzen zesummen.", zh: "我们 一起 跳舞。"},
    {l: 1, e: "🧒 🍦", a: "love", en: "I love ice_cream.", de: "Ich liebe Eis.", lb: "Ech iesse gär Glace.", zh: "我 喜欢 冰淇淋。"},
    {l: 1, e: "🏊", a: "swim", en: "I can swim.", de: "Ich kann schwimmen.", lb: "Ech ka schwammen.", zh: "我 会 游泳。"},
    {l: 1, e: "🐦 🐦", a: "fly", en: "Birds can fly.", de: "Vögel können fliegen.", lb: "Vulle kënne fléien.", zh: "小鸟 会 飞。"},
    // level 2: four or five words, the adjective comes before the noun
    {l: 2, e: "🎈", a: "fly", en: "The balloon is red.", de: "Der Ballon ist rot.", lb: "De Ballon ass rout.", zh: "气球 是 红色的。", x: "blue|blau|blo|蓝色的"},
    {l: 2, e: "🐘", a: "grow", en: "The elephant is big.", de: "Der Elefant ist groß.", lb: "Den Elefant ass grouss.", zh: "大象 很 大。", x: "small|klein|kleng|小"},
    {l: 2, e: "🐭", a: "shrink", en: "The mouse is small.", de: "Die Maus ist klein.", lb: "D'Maus ass kleng.", zh: "老鼠 很 小。", x: "big|groß|grouss|大"},
    {l: 2, e: "🐍", a: "wiggle", en: "The snake is long.", de: "Die Schlange ist lang.", lb: "D'Schlaang ass laang.", zh: "蛇 很 长。", x: "short|kurz|kuerz|短"},
    {l: 2, e: "🦒", a: "stretch", en: "The giraffe is tall.", de: "Die Giraffe ist groß.", lb: "D'Giraff ass grouss.", zh: "长颈鹿 很 高。", x: "small|klein|kleng|矮"},
    {l: 2, e: "🐈‍⬛", a: "spin", en: "The cat is black.", de: "Die Katze ist schwarz.", lb: "D'Kaz ass schwaarz.", zh: "小猫 是 黑色的。", x: "white|weiß|wäiss|白色的"},
    {l: 2, e: "🌸", a: "sway", en: "The flower is pink.", de: "Die Blume ist rosa.", lb: "D'Blumm ass rosa.", zh: "花 是 粉色的。", x: "blue|blau|blo|蓝色的"},
    {l: 2, e: "🚕", a: "drive", en: "The taxi is yellow.", de: "Das Taxi ist gelb.", lb: "Den Taxi ass giel.", zh: "出租车 是 黄色的。", x: "red|rot|rout|红色的"},
    {l: 2, e: "☀️", a: "hot", en: "The sun is hot.", de: "Die Sonne ist heiß.", lb: "D'Sonn ass waarm.", zh: "太阳 很 热。", x: "cold|kalt|kal|冷"},
    {l: 2, e: "🍦", a: "cold", en: "The ice_cream is cold.", de: "Das Eis ist kalt.", lb: "D'Glace ass kal.", zh: "冰淇淋 很 凉。", x: "hot|heiß|waarm|热"},
    {l: 2, e: "🐯", a: "run", en: "The tiger is fast.", de: "Der Tiger ist schnell.", lb: "Den Tiger ass séier.", zh: "老虎 跑得 很 快。", x: "slow|langsam|lues|慢"},
    {l: 2, e: "🐢", a: "crawl", en: "The turtle is slow.", de: "Die Schildkröte ist langsam.", lb: "D'Schildkröt ass lues.", zh: "乌龟 爬得 很 慢。", x: "fast|schnell|séier|快"},
    {l: 2, e: "🐷", a: "roll", en: "The pig is dirty.", de: "Das Schwein ist schmutzig.", lb: "D'Schwäin ass dreckeg.", zh: "小猪 很 脏。", x: "blue|blau|blo|蓝色的"},
    {l: 2, e: "🐵", a: "laugh", en: "The monkey is funny.", de: "Der Affe ist lustig.", lb: "Den Af ass witzeg.", zh: "猴子 很 好玩。", x: "sad|traurig|traureg|难过"},
    {l: 2, e: "🐶", a: "dance", en: "My dog is happy.", de: "Mein Hund ist glücklich.", lb: "Mäin Hond ass frou.", zh: "我的 小狗 很 开心。", x: "sad|traurig|traureg|难过"},
    {l: 2, e: "🐱 🐱", a: "hop", en: "I have two cats.", de: "Ich habe zwei Katzen.", lb: "Ech hunn zwou Kazen.", zh: "我 有 两只 猫。", x: "three|drei|dräi|三只"},
    {l: 2, e: "🚗", a: "drive", en: "I have a red car.", de: "Ich habe ein rotes Auto.", lb: "Ech hunn e rouden Auto.", zh: "我 有 一辆 红色的 汽车。", x: "blue|blaues|bloen|蓝色的"},
    {l: 2, e: "⭐", a: "shine", en: "I see a big star.", de: "Ich sehe einen großen Stern.", lb: "Ech gesinn e grousse Stär.", zh: "我 看见 一颗 大 星星。", x: "small|kleinen|klenge|小"},
    {l: 2, e: "🐸", a: "hop", en: "I see a green frog.", de: "Ich sehe einen grünen Frosch.", lb: "Ech gesinn e grénge Fräsch.", zh: "我 看见 一只 绿色的 青蛙。", x: "red|roten|roude|红色的"},
    {l: 2, e: "👧 🧢", a: "spin", en: "She has a blue cap.", de: "Sie hat eine blaue Kappe.", lb: "Si huet eng blo Kap.", zh: "她 有 一顶 蓝色的 帽子。", x: "red|rote|rout|红色的"},
    {l: 2, e: "🔴", a: "roll", en: "A big red ball.", de: "Ein großer roter Ball.", lb: "E grousse roude Ball.", zh: "一个 红色的 大 球。", x: "small|kleiner|klenge|小"},
    // level 3: six words and more, where things are
    {l: 3, e: "🐱 🛏️", o: "on", a: "sleep", en: "The cat sleeps on the bed.", de: "Die Katze schläft auf dem Bett.", lb: "D'Kaz schléift um Bett.", zh: "小猫 在 床 上 睡觉。", x: "under|unter|ënner|下"},
    {l: 3, e: "🐶 🪑", o: "under", a: "hop", en: "The dog is under the chair.", de: "Der Hund liegt unter dem Stuhl.", lb: "Den Hond läit ënner dem Stull.", zh: "小狗 在 椅子 下面。", x: "on|auf|op|上面"},
    {l: 3, e: "🐭 🛏️", o: "under", a: "shrink", en: "The mouse is under the bed.", de: "Die Maus ist unter dem Bett.", lb: "D'Maus ass ënner dem Bett.", zh: "老鼠 在 床 下面。", x: "on|auf|op|上面"},
    {l: 3, e: "🐦 🌳", o: "in", a: "sing", en: "The bird sits in the tree.", de: "Der Vogel sitzt im Baum.", lb: "De Vull sëtzt am Bam.", zh: "小鸟 在 树 上。", x: "dog|Hund|Hond|小狗"},
    {l: 3, e: "🐟 🌊", o: "in", a: "swim", en: "The fish swims in the water.", de: "Der Fisch schwimmt im Wasser.", lb: "De Fësch schwëmmt am Waasser.", zh: "小鱼 在 水 里 游。", x: "cat|Katze|Kaz|小猫"},
    {l: 3, e: "🦆 🌊", o: "on", a: "swim", en: "The duck swims on the pond.", de: "Die Ente schwimmt auf dem Teich.", lb: "D'Int schwëmmt um Weier.", zh: "鸭子 在 池塘 里 游泳。", x: "frog|Frosch|Fräsch|青蛙"},
    {l: 3, e: "🐸 🌊", o: "in", a: "splash", en: "The frog jumps into the water.", de: "Der Frosch springt ins Wasser.", lb: "De Fräsch spréngt an d'Waasser.", zh: "青蛙 跳 进 水 里。", x: "bird|Vogel|Vull|小鸟"},
    {l: 3, e: "⚽ 📦", o: "next", a: "roll", en: "The ball is next_to the box.", de: "Der Ball liegt neben der Kiste.", lb: "De Ball läit nieft der Këscht.", zh: "球 在 箱子 旁边。", x: "under|unter|ënner|下面"},
    {l: 3, e: "🐮 🐴", o: "next", a: "dance", en: "The cow stands next_to the horse.", de: "Die Kuh steht neben dem Pferd.", lb: "D'Kou steet nieft dem Päerd.", zh: "奶牛 站 在 马 旁边。", x: "pig|Schwein|Schwäin|猪"},
    {l: 3, e: "🐵 🐘", o: "on", a: "hop", en: "The monkey sits on the elephant.", de: "Der Affe sitzt auf dem Elefanten.", lb: "Den Af sëtzt um Elefant.", zh: "猴子 坐 在 大象 身上。", x: "lion|Löwen|Léiw|狮子"},
    {l: 3, e: "🍎 🎒", o: "in", a: "hop", en: "The apple is in my backpack.", de: "Der Apfel ist in meinem Rucksack.", lb: "Den Apel ass a mengem Rucksak.", zh: "苹果 在 我的 书包 里。", x: "banana|Banane|Banann|香蕉"},
    {l: 3, e: "☀️ 🏠", o: "over", a: "shine", en: "The sun is over the house.", de: "Die Sonne ist über dem Haus.", lb: "D'Sonn ass iwwer dem Haus.", zh: "太阳 在 房子 上面。", x: "moon|Mond|Mound|月亮"},
    {l: 3, e: "🚗 🏠", o: "front", a: "drive", en: "The car is in_front_of the house.", de: "Das Auto steht vor dem Haus.", lb: "Den Auto steet virum Haus.", zh: "汽车 停 在 房子 前面。", x: "bus|Bus|Bus|公交车"},
    {l: 3, e: "🐰 ☂️", o: "under", a: "rain", en: "The rabbit is under the umbrella.", de: "Das Kaninchen ist unter dem Regenschirm.", lb: "D'Kanéngchen ass ënner dem Prabbeli.", zh: "兔子 在 雨伞 下面。", x: "on|auf|op|上面"},
    {l: 3, e: "🐧 🧊", o: "on", a: "slide", en: "The penguin slides on the ice.", de: "Der Pinguin rutscht auf dem Eis.", lb: "De Pinguin ass um Äis.", zh: "企鹅 在 冰 上 滑。", x: "swims|schwimmt|schwëmmt|游"},
    {l: 3, e: "🏊 🌊", o: "in", a: "swim", en: "We are swimming in the sea.", de: "Wir schwimmen im Meer.", lb: "Mir schwammen am Mier.", zh: "我们 在 海 里 游泳。", x: "sleeping|schlafen|schlofen|睡觉"},
    {l: 3, e: "🍰 🍽️", o: "on", a: "grow", en: "The cake is on the plate.", de: "Der Kuchen ist auf dem Teller.", lb: "De Kuch ass um Teller.", zh: "蛋糕 在 盘子 上。", x: "bread|Brot|Brout|面包"},
    {l: 3, e: "🦋 🌸", o: "on", a: "fly", en: "The butterfly sits on the flower.", de: "Der Schmetterling sitzt auf der Blume.", lb: "De Päiperlek sëtzt op der Blumm.", zh: "蝴蝶 停 在 花 上。", x: "bird|Vogel|Vull|小鸟"},
    {l: 3, e: "🐔 🚗", o: "on", a: "hop", en: "The chicken sits on the car.", de: "Das Huhn sitzt auf dem Auto.", lb: "D'Hong sëtzt um Auto.", zh: "母鸡 坐 在 汽车 上。", x: "under|unter|ënner|下"},
    {l: 3, e: "🐙 🛁", o: "in", a: "wiggle", en: "The octopus is in the bath.", de: "Der Oktopus ist in der Badewanne.", lb: "Den Oktopus ass an der Bidden.", zh: "章鱼 在 浴缸 里。", x: "fish|Fisch|Fësch|鱼"},
    {l: 3, e: "⚽ 🐶 🐱", o: "between", a: "roll", en: "The ball is between the dog and the cat.", de: "Der Ball liegt zwischen dem Hund und der Katze.", lb: "De Ball läit tëscht dem Hond an der Kaz.", zh: "球 在 小狗 和 小猫 中间。", x: "horse|Pferd|Päerd|马"}
  ]
};
