/* L'Île aux Mots : mots, thèmes, jeux et constantes. */
const VERSION = "1.5";
// Google Sheet collector (Apps Script web app URL ending in /exec, see outils/collecteur.gs). Empty = off.
const COLLECTE = {url: ""};
/* ---------- words: emoji|english|français|中文 ---------- */
const P = s => s.trim().split("\n").map(l => { const [e,en,fr,zh] = l.trim().split("|"); return {e,en,fr,zh}; });
const THEMES = {  // generated by outils/generer_mots.py from donnees/lexique.json: edit the lexicon, not this block
  animals:{label:"Animaux", icon:"🐱", words:[
    {"e":"🐱","en":"cat","fr":"chat","zh":"猫","de":"die Katze","lb":"d'Kaz","lvl":1,"lod":"KAZ1"},
    {"e":"🐶","en":"dog","fr":"chien","zh":"狗","de":"der Hund","lb":"den Hond","lvl":1,"lod":"HOND1"},
    {"e":"🐮","en":"cow","fr":"vache","zh":"奶牛","de":"die Kuh","lb":"d'Kou","lvl":1,"lod":"KOU1"},
    {"e":"🐷","en":"pig","fr":"cochon","zh":"猪","de":"das Schwein","lb":"d'Schwäin","lvl":1,"lod":"SCHWAIN1"},
    {"e":"🦆","en":"duck","fr":"canard","zh":"鸭子","de":"die Ente","lb":"d'Int","lvl":1,"lod":"INT1"},
    {"e":"🐴","en":"horse","fr":"cheval","zh":"马","de":"das Pferd","lb":"d'Päerd","lvl":1,"lod":"PAERD1"},
    {"e":"🦁","en":"lion","fr":"lion","zh":"狮子","de":"der Löwe","lb":"de Léiw","lvl":1,"lod":"LEIW1"},
    {"e":"🐸","en":"frog","fr":"grenouille","zh":"青蛙","de":"der Frosch","lb":"de Fräsch","lvl":1,"lod":"FRASCH1"},
    {"e":"🐟","en":"fish","fr":"poisson","zh":"鱼","de":"der Fisch","lb":"de Fësch","lvl":1,"lod":"FESCH1"},
    {"e":"🐦","en":"bird","fr":"oiseau","zh":"鸟","de":"der Vogel","lb":"de Vull","lvl":1,"lod":"VULL1"},
    {"e":"🐰","en":"rabbit","fr":"lapin","zh":"兔子","de":"das Kaninchen","lb":"d'Kanéngchen","lvl":1,"lod":"KANENGCHEN1"},
    {"e":"🐵","en":"monkey","fr":"singe","zh":"猴子","de":"der Affe","lb":"den Af","lvl":1,"lod":"AF1"},
    {"e":"🐘","en":"elephant","fr":"éléphant","zh":"大象","de":"der Elefant","lb":"den Elefant","lvl":1,"lod":"ELEFANT1"},
    {"e":"🐻","en":"bear","fr":"ours","zh":"熊","de":"der Bär","lb":"de Bier","lvl":1,"lod":"BIER1"},
    {"e":"🐭","en":"mouse","fr":"souris","zh":"老鼠","de":"die Maus","lb":"d'Maus","lvl":1,"lod":"MAUS1"},
    {"e":"🐑","en":"sheep","fr":"mouton","zh":"羊","de":"das Schaf","lb":"d'Schof","lvl":1,"lod":"SCHOF1"},
    {"e":"🐔","en":"chicken","fr":"poule","zh":"鸡","de":"das Huhn","lb":"d'Hong","lvl":1,"lod":"HONG1"},
    {"e":"🐯","en":"tiger","fr":"tigre","zh":"老虎","de":"der Tiger","lb":"den Tiger","lvl":2,"lod":"TIGER1"},
    {"e":"🦒","en":"giraffe","fr":"girafe","zh":"长颈鹿","de":"die Giraffe","lb":"d'Giraff","lvl":2,"lod":"GIRAFF1"},
    {"e":"🦓","en":"zebra","fr":"zèbre","zh":"斑马","de":"das Zebra","lb":"den Zeebra","lvl":2,"lod":"ZEEBRA1"},
    {"e":"🐍","en":"snake","fr":"serpent","zh":"蛇","de":"die Schlange","lb":"d'Schlaang","lvl":2,"lod":"SCHLAANG1"},
    {"e":"🦋","en":"butterfly","fr":"papillon","zh":"蝴蝶","de":"der Schmetterling","lb":"de Päiperlek","lvl":2,"lod":"PAIPERLEK1"},
    {"e":"🐧","en":"penguin","fr":"pingouin","zh":"企鹅","de":"der Pinguin","lb":"de Pinguin","lvl":2,"lod":"PINGUIN1"},
    {"e":"🐢","en":"turtle","fr":"tortue","zh":"乌龟","de":"die Schildkröte","lb":"d'Schildkröt","lvl":2,"lod":"SCHILDKROT1"},
    {"e":"🦉","en":"owl","fr":"hibou","zh":"猫头鹰","de":"die Eule","lb":"d'Eil","lvl":2,"lod":"EIL1"},
    {"e":"🐬","en":"dolphin","fr":"dauphin","zh":"海豚","de":"der Delfin","lb":"den Delfin","lvl":2,"lod":"DELFIN1"},
    {"e":"🐳","en":"whale","fr":"baleine","zh":"鲸鱼","de":"der Wal","lb":"de Wal","lvl":2,"lod":"WAL2"},
    {"e":"🐙","en":"octopus","fr":"pieuvre","zh":"章鱼","de":"der Oktopus","lb":"den Oktopus","lvl":3,"lod":"OKTOPUS1"},
    {"e":"🦘","en":"kangaroo","fr":"kangourou","zh":"袋鼠","de":"das Känguru","lb":"de Känguru","lvl":3,"lod":"KANGURU1"},
    {"e":"🐊","en":"crocodile","fr":"crocodile","zh":"鳄鱼","de":"das Krokodil","lb":"de Krokodil","lvl":3,"lod":"KROKODIL1"}
  ]},
  food:{label:"Miam", icon:"🍎", words:[
    {"e":"🍎","en":"apple","fr":"pomme","zh":"苹果","de":"der Apfel","lb":"den Apel","lvl":1,"lod":"APEL1"},
    {"e":"🍌","en":"banana","fr":"banane","zh":"香蕉","de":"die Banane","lb":"d'Banann","lvl":1,"lod":"BANANN1"},
    {"e":"🍓","en":"strawberry","fr":"fraise","zh":"草莓","de":"die Erdbeere","lb":"d'Äerdbier","lvl":1,"lod":"AERDBIER1"},
    {"e":"🍇","en":"grapes","fr":"raisin","zh":"葡萄","de":"die Trauben","lb":"d'Drauwen","lvl":1,"lod":"DRAUF1"},
    {"e":"🍊","en":"orange","fr":"orange","zh":"橙子","de":"die Orange","lb":"d'Orange","lvl":1,"lod":"ORANGE1"},
    {"e":"🍐","en":"pear","fr":"poire","zh":"梨","de":"die Birne","lb":"d'Bier","lvl":1,"lod":"BIER3"},
    {"e":"🍒","en":"cherries","fr":"cerises","zh":"樱桃","de":"die Kirschen","lb":"d'Kiischten","lvl":1,"lod":"KIISCHT1"},
    {"e":"🍉","en":"watermelon","fr":"pastèque","zh":"西瓜","de":"die Wassermelone","lb":"d'Waassermeloun","lvl":1,"lod":"WAASSERMELOUN1"},
    {"e":"🍞","en":"bread","fr":"pain","zh":"面包","de":"das Brot","lb":"d'Brout","lvl":1,"lod":"BROUT1"},
    {"e":"🧀","en":"cheese","fr":"fromage","zh":"奶酪","de":"der Käse","lb":"de Kéis","lvl":1,"lod":"KEIS1"},
    {"e":"🥛","en":"milk","fr":"lait","zh":"牛奶","de":"die Milch","lb":"d'Mëllech","lvl":1,"lod":"MELLECH1"},
    {"e":"🥚","en":"egg","fr":"œuf","zh":"鸡蛋","de":"das Ei","lb":"d'Ee","lvl":1,"lod":"EE1"},
    {"e":"🍰","en":"cake","fr":"gâteau","zh":"蛋糕","de":"der Kuchen","lb":"de Kuch","lvl":1,"lod":"KUCH1"},
    {"e":"🥕","en":"carrot","fr":"carotte","zh":"胡萝卜","de":"die Karotte","lb":"d'Muert","lvl":1,"lod":"MUERT1"},
    {"e":"🍕","en":"pizza","fr":"pizza","zh":"披萨","de":"die Pizza","lb":"d'Pizza","lvl":1,"lod":"PIZZA1"},
    {"e":"🍅","en":"tomato","fr":"tomate","zh":"西红柿","de":"die Tomate","lb":"d'Tomat","lvl":1,"lod":"TOMAT1"},
    {"e":"🍦","en":"ice cream","fr":"glace","zh":"冰淇淋","de":"das Eis","lb":"d'Glace","lvl":1,"lod":"GLACE2"},
    {"e":"🥔","en":"potato","fr":"pomme de terre","zh":"土豆","de":"die Kartoffel","lb":"d'Gromper","lvl":2,"lod":"GROMPER1"},
    {"e":"🍋","en":"lemon","fr":"citron","zh":"柠檬","de":"die Zitrone","lb":"d'Zitroun","lvl":2,"lod":"ZITROUN1"},
    {"e":"🍑","en":"peach","fr":"pêche","zh":"桃子","de":"der Pfirsich","lb":"d'Piisch","lvl":2,"lod":"PIISCH1"},
    {"e":"🥪","en":"sandwich","fr":"sandwich","zh":"三明治","de":"das Sandwich","lb":"de Sandwich","lvl":2,"lod":"SANDWICH1"},
    {"e":"🍜","en":"noodles","fr":"nouilles","zh":"面条","de":"die Nudeln","lb":"d'Nuddelen","lvl":2,"lod":"NUDDEL1"},
    {"e":"🍚","en":"rice","fr":"riz","zh":"米饭","de":"der Reis","lb":"de Räis","lvl":2,"lod":"RAIS1"},
    {"e":"🥒","en":"cucumber","fr":"concombre","zh":"黄瓜","de":"die Gurke","lb":"d'Concomber","lvl":3,"lod":"CONCOMBER1"},
    {"e":"🍄","en":"mushroom","fr":"champignon","zh":"蘑菇","de":"der Pilz","lb":"de Champignon","lvl":3,"lod":"CHAMPIGNON1"},
    {"e":"🍍","en":"pineapple","fr":"ananas","zh":"菠萝","de":"die Ananas","lb":"d'Ananas","lvl":3,"lod":"ANANAS1"},
    {"e":"🥦","en":"broccoli","fr":"brocoli","zh":"西兰花","de":"der Brokkoli","lb":"de Brokkoli","lvl":3,"lod":"BROKKOLI1"}
  ]},
  colors:{label:"Couleurs", icon:"🎨", words:[
    {"e":"#E53935","en":"red","fr":"rouge","zh":"红色","de":"rot","lb":"rout","lvl":1,"lod":"ROUT1"},
    {"e":"#1E88E5","en":"blue","fr":"bleu","zh":"蓝色","de":"blau","lb":"blo","lvl":1,"lod":"BLO1"},
    {"e":"#43A047","en":"green","fr":"vert","zh":"绿色","de":"grün","lb":"gréng","lvl":1,"lod":"GRENG1"},
    {"e":"#FDD835","en":"yellow","fr":"jaune","zh":"黄色","de":"gelb","lb":"giel","lvl":1,"lod":"GIEL1"},
    {"e":"#FB8C00","en":"orange","fr":"orange","zh":"橙色","de":"orange","lb":"orange","lvl":1,"lod":"ORANGE2"},
    {"e":"#F48FB1","en":"pink","fr":"rose","zh":"粉色","de":"rosa","lb":"rosa","lvl":1,"lod":"ROSA1"},
    {"e":"#8E24AA","en":"purple","fr":"violet","zh":"紫色","de":"lila","lb":"mof","lvl":1,"lod":"MOF1"},
    {"e":"#212121","en":"black","fr":"noir","zh":"黑色","de":"schwarz","lb":"schwaarz","lvl":1,"lod":"SCHWAARZ1"},
    {"e":"#FFFFFF","en":"white","fr":"blanc","zh":"白色","de":"weiß","lb":"wäiss","lvl":1,"lod":"WAISS1"},
    {"e":"#795548","en":"brown","fr":"marron","zh":"棕色","de":"braun","lb":"brong","lvl":1,"lod":"BRONG1"},
    {"e":"#757575","en":"grey","fr":"gris","zh":"灰色","de":"grau","lb":"gro","lvl":1,"lod":"GRO1"},
    {"e":"#D4AF37","en":"gold","fr":"doré","zh":"金色","de":"golden","lb":"gëllen","lvl":3,"lod":"GELLEN1"},
    {"e":"#C0C0C0","en":"silver","fr":"argenté","zh":"银色","de":"silbern","lb":"sëlwereg","lvl":3,"lod":"SELWEREG1"}
  ]},
  body:{label:"Mon corps", icon:"👃", words:[
    {"e":"👀","en":"eyes","fr":"yeux","zh":"眼睛","de":"die Augen","lb":"d'Aen","lvl":1,"lod":"A1"},
    {"e":"👃","en":"nose","fr":"nez","zh":"鼻子","de":"die Nase","lb":"d'Nues","lvl":1,"lod":"NUES1"},
    {"e":"👄","en":"mouth","fr":"bouche","zh":"嘴巴","de":"der Mund","lb":"de Mond","lvl":1,"lod":"MOND1"},
    {"e":"👂","en":"ear","fr":"oreille","zh":"耳朵","de":"das Ohr","lb":"d'Ouer","lvl":1,"lod":"OUER1"},
    {"e":"✋","en":"hand","fr":"main","zh":"手","de":"die Hand","lb":"d'Hand","lvl":1,"lod":"HAND1"},
    {"e":"🦶","en":"foot","fr":"pied","zh":"脚","de":"der Fuß","lb":"de Fouss","lvl":1,"lod":"FOUSS1"},
    {"e":"🦷","en":"tooth","fr":"dent","zh":"牙齿","de":"der Zahn","lb":"den Zant","lvl":1,"lod":"ZANT1"},
    {"e":"💪","en":"arm","fr":"bras","zh":"胳膊","de":"der Arm","lb":"den Aarm","lvl":1,"lod":"AARM2"},
    {"e":"🦵","en":"leg","fr":"jambe","zh":"腿","de":"das Bein","lb":"d'Been","lvl":1,"lod":"BEEN1"},
    {"e":"💇","en":"hair","fr":"cheveux","zh":"头发","de":"die Haare","lb":"d'Hoer","lvl":1,"lod":"HOER1"},
    {"e":"👅","en":"tongue","fr":"langue","zh":"舌头","de":"die Zunge","lb":"d'Zong","lvl":2,"lod":"ZONG1"},
    {"e":"👆","en":"finger","fr":"doigt","zh":"手指","de":"der Finger","lb":"de Fanger","lvl":2,"lod":"FANGER1"},
    {"e":"🙂","en":"face","fr":"visage","zh":"脸","de":"das Gesicht","lb":"d'Gesiicht","lvl":2,"lod":"GESIICHT1"},
    {"e":"🦴","en":"bone","fr":"os","zh":"骨头","de":"der Knochen","lb":"d'Schank","lvl":2,"lod":"SCHANK1"},
    {"e":"🫀","en":"heart","fr":"cœur","zh":"心脏","de":"das Herz","lb":"d'Häerz","lvl":3,"lod":"HAERZ1"},
    {"e":"🧠","en":"brain","fr":"cerveau","zh":"大脑","de":"das Gehirn","lb":"d'Gehier","lvl":3,"lod":"GEHIER1"}
  ]},
  things:{label:"Mon monde", icon:"⚽", words:[
    {"e":"⚽","en":"ball","fr":"ballon","zh":"球","de":"der Ball","lb":"de Ball","lvl":1,"lod":"BALL1"},
    {"e":"🚗","en":"car","fr":"voiture","zh":"汽车","de":"das Auto","lb":"den Auto","lvl":1,"lod":"AUTO1"},
    {"e":"🚲","en":"bike","fr":"vélo","zh":"自行车","de":"das Fahrrad","lb":"de Vëlo","lvl":1,"lod":"VELO1"},
    {"e":"⛵","en":"boat","fr":"bateau","zh":"船","de":"das Boot","lb":"d'Boot","lvl":1,"lod":"BOOT1"},
    {"e":"✈️","en":"plane","fr":"avion","zh":"飞机","de":"das Flugzeug","lb":"de Fliger","lvl":1,"lod":"FLIGER1"},
    {"e":"🚂","en":"train","fr":"train","zh":"火车","de":"der Zug","lb":"den Zuch","lvl":1,"lod":"ZUCH1"},
    {"e":"📖","en":"book","fr":"livre","zh":"书","de":"das Buch","lb":"d'Buch","lvl":1,"lod":"BUCH1"},
    {"e":"🏠","en":"house","fr":"maison","zh":"房子","de":"das Haus","lb":"d'Haus","lvl":1,"lod":"HAUS1"},
    {"e":"🌳","en":"tree","fr":"arbre","zh":"树","de":"der Baum","lb":"de Bam","lvl":1,"lod":"BAM1"},
    {"e":"🌸","en":"flower","fr":"fleur","zh":"花","de":"die Blume","lb":"d'Blumm","lvl":1,"lod":"BLUMM1"},
    {"e":"☀️","en":"sun","fr":"soleil","zh":"太阳","de":"die Sonne","lb":"d'Sonn","lvl":1,"lod":"SONN1"},
    {"e":"🌙","en":"moon","fr":"lune","zh":"月亮","de":"der Mond","lb":"de Mound","lvl":1,"lod":"MOUND1"},
    {"e":"⭐","en":"star","fr":"étoile","zh":"星星","de":"der Stern","lb":"de Stär","lvl":1,"lod":"STAR1"},
    {"e":"🚌","en":"bus","fr":"bus","zh":"公交车","de":"der Bus","lb":"de Bus","lvl":1,"lod":"BUS1"},
    {"e":"☁️","en":"cloud","fr":"nuage","zh":"云","de":"die Wolke","lb":"d'Wollek","lvl":1,"lod":"WOLLEK1"},
    {"e":"☂️","en":"umbrella","fr":"parapluie","zh":"雨伞","de":"der Regenschirm","lb":"de Prabbeli","lvl":2,"lod":"PRABBELI1"},
    {"e":"🌈","en":"rainbow","fr":"arc-en-ciel","zh":"彩虹","de":"der Regenbogen","lb":"de Reebou","lvl":2,"lod":"REEBOU1"},
    {"e":"🔑","en":"key","fr":"clé","zh":"钥匙","de":"der Schlüssel","lb":"de Schlëssel","lvl":2,"lod":"SCHLESSEL1"},
    {"e":"👓","en":"glasses","fr":"lunettes","zh":"眼镜","de":"die Brille","lb":"de Brëll","lvl":2,"lod":"BRELL1"},
    {"e":"✏️","en":"pencil","fr":"crayon","zh":"铅笔","de":"der Bleistift","lb":"de Bläistëft","lvl":2,"lod":"BLAISTEFT1"},
    {"e":"✂️","en":"scissors","fr":"ciseaux","zh":"剪刀","de":"die Schere","lb":"d'Schéier","lvl":2,"lod":"SCHEIER2"},
    {"e":"🕰️","en":"clock","fr":"horloge","zh":"钟","de":"die Uhr","lb":"d'Auer","lvl":2,"lod":"AUER1"},
    {"e":"🚀","en":"rocket","fr":"fusée","zh":"火箭","de":"die Rakete","lb":"d'Rakéit","lvl":2,"lod":"RAKEIT1"},
    {"e":"⛄","en":"snowman","fr":"bonhomme de neige","zh":"雪人","de":"der Schneemann","lb":"de Schnéimännchen","lvl":2,"lod":"SCHNEIMANNCHEN1"},
    {"e":"🚁","en":"helicopter","fr":"hélicoptère","zh":"直升机","de":"der Hubschrauber","lb":"den Helikopter","lvl":3,"lod":"HELIKOPTER1"},
    {"e":"🎒","en":"backpack","fr":"sac à dos","zh":"书包","de":"der Rucksack","lb":"de Rucksak","lvl":3,"lod":"RUCKSAK1"}
  ]},
  clothes:{label:"Vêtements", icon:"👕", words:[
    {"e":"🎩","en":"hat","fr":"chapeau","zh":"帽子","de":"der Hut","lb":"den Hutt","lvl":1,"lod":"HUTT1"},
    {"e":"👕","en":"T-shirt","fr":"T-shirt","zh":"T恤","de":"das T-Shirt","lb":"den T-Shirt","lvl":1,"lod":"TSHIRT1"},
    {"e":"👗","en":"dress","fr":"robe","zh":"裙子","de":"das Kleid","lb":"d'Kleed","lvl":1,"lod":"KLEED1"},
    {"e":"👟","en":"shoes","fr":"chaussures","zh":"鞋子","de":"die Schuhe","lb":"d'Schong","lvl":1,"lod":"SCHONG1"},
    {"e":"🧦","en":"socks","fr":"chaussettes","zh":"袜子","de":"die Socken","lb":"d'Strëmp","lvl":1,"lod":"STREMP1"},
    {"e":"🧥","en":"coat","fr":"manteau","zh":"外套","de":"der Mantel","lb":"de Mantel","lvl":1,"lod":"MANTEL1"},
    {"e":"🧣","en":"scarf","fr":"écharpe","zh":"围巾","de":"der Schal","lb":"de Schal","lvl":2,"lod":"SCHAL1"},
    {"e":"🧤","en":"gloves","fr":"gants","zh":"手套","de":"die Handschuhe","lb":"d'Händschen","lvl":2,"lod":"HANDSCH1"},
    {"e":"🧢","en":"cap","fr":"casquette","zh":"鸭舌帽","de":"die Kappe","lb":"d'Kap","lvl":2,"lod":"KAP1"},
    {"e":"👓","en":"glasses","fr":"lunettes","zh":"眼镜","de":"die Brille","lb":"de Brëll","lvl":2,"lod":"BRELL1"},
    {"e":"👢","en":"boots","fr":"bottes","zh":"靴子","de":"die Stiefel","lb":"d'Stiwwelen","lvl":2,"lod":"STIWWEL1"},
    {"e":"👖","en":"trousers","fr":"pantalon","zh":"裤子","de":"die Hose","lb":"d'Box","lvl":2,"lod":"BOX1"},
    {"e":"👔","en":"tie","fr":"cravate","zh":"领带","de":"die Krawatte","lb":"d'Krawatt","lvl":3,"lod":"KRAWATT1"}
  ]},
  jobs:{label:"Métiers", icon:"🧑‍🚀", words:[
    {"e":"🧑‍⚕️","en":"doctor","fr":"docteur","zh":"医生","de":"der Arzt","lb":"den Dokter","lvl":1,"lod":"DOKTER1"},
    {"e":"🧑‍🏫","en":"teacher","fr":"maîtresse","zh":"老师","de":"die Lehrerin","lb":"d'Joffer","lvl":1,"lod":"JOFFER1"},
    {"e":"🧑‍🌾","en":"farmer","fr":"fermier","zh":"农民","de":"der Bauer","lb":"de Bauer","lvl":1,"lod":"BAUER1"},
    {"e":"🧑‍🍳","en":"cook","fr":"cuisinier","zh":"厨师","de":"der Koch","lb":"de Kach","lvl":2,"lod":"KACH1"},
    {"e":"👮","en":"police officer","fr":"policier","zh":"警察","de":"der Polizist","lb":"de Polizist","lvl":2,"lod":"POLIZIST1"},
    {"e":"🧑‍🚒","en":"firefighter","fr":"pompier","zh":"消防员","de":"der Feuerwehrmann","lb":"de Pompjee","lvl":2,"lod":"POMPJEE1"},
    {"e":"🧑‍✈️","en":"pilot","fr":"pilote","zh":"飞行员","de":"der Pilot","lb":"de Pilot","lvl":2,"lod":"PILOT1"},
    {"e":"🧑‍🎤","en":"singer","fr":"chanteur","zh":"歌手","de":"der Sänger","lb":"de Sänger","lvl":2,"lod":"SANGER1"},
    {"e":"🧑‍🚀","en":"astronaut","fr":"astronaute","zh":"宇航员","de":"der Astronaut","lb":"den Astronaut","lvl":3,"lod":"ASTRONAUT1"},
    {"e":"🧑‍🎨","en":"artist","fr":"peintre","zh":"画家","de":"der Künstler","lb":"de Kënschtler","lvl":3,"lod":"KENSCHTLER1"},
    {"e":"🧑‍🔬","en":"scientist","fr":"scientifique","zh":"科学家","de":"der Wissenschaftler","lb":"de Wëssenschaftler","lvl":3,"lod":"WESSENSCHAFTLER1"},
    {"e":"🧑‍🔧","en":"mechanic","fr":"mécanicien","zh":"修理工","de":"der Mechaniker","lb":"de Mecanicien","lvl":3,"lod":"MECANICIEN1"}
  ]},
  actions:{label:"Actions", icon:"🏃", words:[
    {"e":"🏃","en":"run","fr":"courir","zh":"跑步","de":"laufen","lb":"lafen","lvl":1,"lod":"LAFEN1"},
    {"e":"😴","en":"sleep","fr":"dormir","zh":"睡觉","de":"schlafen","lb":"schlofen","lvl":1,"lod":"SCHLOFEN1"},
    {"e":"🍽️","en":"eat","fr":"manger","zh":"吃","de":"essen","lb":"iessen","lvl":1,"lod":"IESSEN3"},
    {"e":"🥤","en":"drink","fr":"boire","zh":"喝","de":"trinken","lb":"drénken","lvl":1,"lod":"DRENKEN1"},
    {"e":"🦘","en":"jump","fr":"sauter","zh":"跳","de":"springen","lb":"sprangen","lvl":1,"lod":"SPRANGEN1"},
    {"e":"🏊","en":"swim","fr":"nager","zh":"游泳","de":"schwimmen","lb":"schwammen","lvl":2,"lod":"SCHWAMMEN1"},
    {"e":"🎤","en":"sing","fr":"chanter","zh":"唱歌","de":"singen","lb":"sangen","lvl":2,"lod":"SANGEN1"},
    {"e":"💃","en":"dance","fr":"danser","zh":"跳舞","de":"tanzen","lb":"danzen","lvl":2,"lod":"DANZEN1"},
    {"e":"😭","en":"cry","fr":"pleurer","zh":"哭","de":"weinen","lb":"kräischen","lvl":2,"lod":"KRAISCHEN1"},
    {"e":"😆","en":"laugh","fr":"rire","zh":"笑","de":"lachen","lb":"laachen","lvl":2,"lod":"LAACHEN1"},
    {"e":"✍️","en":"write","fr":"écrire","zh":"写字","de":"schreiben","lb":"schreiwen","lvl":2,"lod":"SCHREIWEN1"},
    {"e":"🧗","en":"climb","fr":"grimper","zh":"爬","de":"klettern","lb":"kloteren","lvl":3,"lod":"KLOTEREN1"},
    {"e":"🧑‍🍳","en":"cook","fr":"cuisiner","zh":"做饭","de":"kochen","lb":"kachen","lvl":3,"lod":"KACHEN2"}
  ]}
};
const NUMS = ["one","two","three","four","five","six","seven","eight","nine","ten"];
const NUMS_FR = ["un","deux","trois","quatre","cinq","six","sept","huit","neuf","dix"];
const NUMS_ZH = ["一","二","三","四","五","六","七","八","九","十"];
const SIMON = P(`👃|Touch your nose!|Touche ton nez|摸摸你的鼻子
👏|Clap your hands!|Tape dans tes mains|拍拍手
🦘|Jump!|Saute|跳一跳
🔄|Turn around!|Tourne sur toi|转个圈
🪑|Sit down!|Assieds-toi|坐下
🧍|Stand up!|Lève-toi|站起来
👋|Wave hello!|Fais coucou|挥挥手
🦶|Stomp your feet!|Tape des pieds|跺跺脚
🙆|Touch your head!|Touche ta tête|摸摸你的头
😑|Close your eyes!|Ferme les yeux|闭上眼睛
🙌|Put your hands up!|Lève les mains|举起手
😝|Stick out your tongue!|Tire la langue|吐舌头`);
const STICKERS = ["🦄","🚀","🦖","🐙","🌈","🏰","🍦","🎈","🦋","🐳","🦕","🚁","🧸","🍭","🐧","🎸","🦜","🛸","🐢","🍩","🐉","🎠","🧁","🪐"];
const PRAISE = ["Great job!","Well done!","Yes!","Super!","Amazing!","You got it!"];

const ACTS = [
  {id:"imagier", multi:true, em:"📚", name:"Imagier", desc:"Touche une image, elle parle", themes:true},
  {id:"ecoute", multi:true,  em:"👂", name:"Écoute & trouve", desc:"Trouve la bonne image", themes:true},
  {id:"ballons", multi:true, em:"🎈", name:"Ballons", desc:"Éclate la bonne couleur"},
  {id:"compte",  em:"🔢", name:"Combien ?", desc:"Compte en anglais"},
  {id:"memory", multi:true,  em:"🃏", name:"Memory", desc:"Retrouve les paires", themes:true},
  {id:"simon",   em:"🙆", name:"Jacques a dit", desc:"Bouge ton corps", badge:"avec un parent"},
  {id:"repete", multi:true,  em:"🎤", name:"Répète !", desc:"Dis le mot à voix haute", themes:true, mic:true}
];
// speech recognition needs a secure page outside claude.ai: the PC at http://localhost, or a future https site
const SR = window.SpeechRecognition || window.webkitSpeechRecognition;
const MIC_OK = !!SR && !window.claude && window.isSecureContext;
const KID_DEFAULT = {
  p7:{name:"Le grand", age:7, ava:"🦊", bridge:"zh", choices:4, showWord:true},
  p4:{name:"La petite", age:4, ava:"🐣", bridge:"fr", choices:3, showWord:false}
};
const FB_TAGS = ["Adoré","Trop facile","Trop dur","Ennui","Son / voix","Bug","Idée"];


const COUNT_ITEMS = [["🐱","cats"],["🐶","dogs"],["🐷","pigs"],["🦆","ducks"],["🐸","frogs"],["🐰","rabbits"],["🍎","apples"],["🍌","bananas"],["🍓","strawberries"],["🥕","carrots"],["⭐","stars"],["🚗","cars"],["🎈","balloons"]];
