/* L'Île aux Mots : tous les textes de l'interface, dans chaque langue apprise (en, de, lb, zh).
   Kezhan : « pour une langue donnée, tout le texte change de langue, sur tout le site ». Pas de français. */
const UI = {
  appTitle:     {en:"Word Island", de:"Wörterinsel", lb:"Wierderinsel", zh:"单词岛"},
  parentsBtn:   {en:"🔒 Parents · hold", de:"🔒 Eltern · lange drücken", lb:"🔒 Elteren · laang drécken", zh:"🔒 家长 · 长按"},
  parentsAria:  {en:"Parents' corner: hold for 2 seconds", de:"Elternbereich: 2 Sekunden gedrückt halten", lb:"Eltereneck: 2 Sekonne gedréckt halen", zh:"家长专区：按住两秒"},
  flagsAria:    {en:"Language", de:"Sprache", lb:"Sprooch", zh:"语言"},
  speedAria:    {en:"Voice speed", de:"Sprechtempo", lb:"Tempo vun der Stëmm", zh:"语速"},
  speedSlow:    {en:"Very slow", de:"Sehr langsam", lb:"Ganz lues", zh:"很慢"},
  speedMid:     {en:"Slow", de:"Langsam", lb:"Lues", zh:"慢一点"},
  speedFast:    {en:"Normal", de:"Normal", lb:"Normal", zh:"正常"},
  homeHint:     {en:"Choose your explorer, then an island!", de:"Wähle deinen Entdecker, dann eine Insel!", lb:"Wiel däin Entdecker, dann eng Insel!", zh:"选择你的探险家，再选一个岛！"},
  chooseIsland: {en:n => `${n}, choose an island!`, de:n => `${n}, wähle eine Insel!`, lb:n => `${n}, wiel eng Insel!`, zh:n => `${n}，选一个岛吧！`},
  hello:        {en:n => `Hello ${n}!`, de:n => `Hallo ${n}!`, lb:n => `Moien ${n}!`, zh:n => `你好，${n}！`},
  bigKid:       {en:"The big one", de:"Der Große", lb:"De Groussen", zh:"哥哥"},
  littleKid:    {en:"The little one", de:"Die Kleine", lb:"D'Kleng", zh:"妹妹"},
  nextSticker:  {en:n => `next sticker in ${n}`, de:n => `nächster Sticker in ${n}`, lb:n => `nächste Sticker an ${n}`, zh:n => `再得${n}颗星换贴纸`},
  lvl:          {en:n => `Lvl ${n}`, de:n => `Stufe ${n}`, lb:n => `Niveau ${n}`, zh:n => `第${n}级`},
  isNew:        {en:"New!", de:"Neu!", lb:"Nei!", zh:"新！"},
  inEnglish:    {en:"in English", de:"auf Englisch", lb:"op Englesch", zh:"英语"},
  back:         {en:"Back", de:"Zurück", lb:"Zeréck", zh:"返回"},
  quit:         {en:"Quit", de:"Beenden", lb:"Ophalen", zh:"退出"},
  whichWorld:   {en:"Which world?", de:"Welche Welt?", lb:"Wéi eng Welt?", zh:"哪个世界？"},
  listen:       {en:"Listen", de:"Hör zu", lb:"Lauschter", zh:"听"},
  didYouLike:   {en:"Did you like it?", de:"Hat es dir gefallen?", lb:"Huet et der gefall?", zh:"你喜欢吗？"},
  loved:        {en:"I loved it", de:"Toll", lb:"Super", zh:"很喜欢"},
  soso:         {en:"It was OK", de:"Geht so", lb:"Et geet", zh:"还行"},
  notLiked:     {en:"Not really", de:"Nicht so", lb:"Net sou", zh:"不太喜欢"},
  again:        {en:"🔁 Again", de:"🔁 Nochmal", lb:"🔁 Nach eng Kéier", zh:"🔁 再玩一次"},
  islands:      {en:"🏝️ Islands", de:"🏝️ Inseln", lb:"🏝️ Inselen", zh:"🏝️ 小岛"},
  thanksLove:   {en:"Yay! Thank you!", de:"Juhu! Danke!", lb:"Juhu! Merci!", zh:"耶！谢谢！"},
  thanks:       {en:"Thank you!", de:"Danke!", lb:"Merci!", zh:"谢谢！"},
  newRecord:    {en:"New record!", de:"Neuer Rekord!", lb:"Neie Rekord!", zh:"新纪录！"},
  recordToast:  {en:n => `New record: ⭐ ${n}`, de:n => `Neuer Rekord: ⭐ ${n}`, lb:n => `Neie Rekord: ⭐ ${n}`, zh:n => `新纪录：⭐ ${n}`},
  levelTitle:   {en:n => `Level ${n}!`, de:n => `Stufe ${n}!`, lb:n => `Niveau ${n}!`, zh:n => `第${n}级！`},
  levelUp:      {en:n => `Level ${n} unlocked!`, de:n => `Stufe ${n} freigeschaltet!`, lb:n => `Niveau ${n} fräigeschalt!`, zh:n => `解锁第${n}级！`},
  levelDown:    {en:n => `Back to level ${n} to practise`, de:n => `Zurück zu Stufe ${n} zum Üben`, lb:n => `Zeréck op Niveau ${n} fir ze üben`, zh:n => `回到第${n}级再练练`},
  endSub:       {en:(ok, n, s) => `${ok} of ${n} first time · ⭐ ${s}`, de:(ok, n, s) => `${ok} von ${n} beim ersten Mal · ⭐ ${s}`,
                 lb:(ok, n, s) => `${ok} vun ${n} beim éischte Mol · ⭐ ${s}`, zh:(ok, n, s) => `${n}题中${ok}题一次答对 · ⭐ ${s}`},
  newSticker:   {en:s => `New sticker! ${s}`, de:s => `Neuer Sticker! ${s}`, lb:s => `Neie Sticker! ${s}`, zh:s => `新贴纸！${s}`},
  storageFull:  {en:"Storage full: tell Claude", de:"Speicher voll: Claude Bescheid sagen", lb:"Späicher voll: dem Claude Bescheed soen", zh:"存储已满：请告诉 Claude"},
  unreachable:  {en:"Logbook unreachable: feedback waits in this browser.", de:"Logbuch nicht erreichbar: Rückmeldungen warten in diesem Browser.",
                 lb:"Logbuch net erreechbar: d'Réckmeldunge waarden an dësem Browser.", zh:"无法连接日志：反馈暂存在此浏览器中。"},
  storeArtifact:{en:"Feedback saved online on claude.ai.", de:"Rückmeldungen online auf claude.ai gespeichert.", lb:"Réckmeldungen online op claude.ai gespäichert.", zh:"反馈已在线保存到 claude.ai。"},
  storeServer:  {en:"Feedback saved on the PC, in the retours folder.", de:"Rückmeldungen auf dem PC gespeichert, im Ordner retours.",
                 lb:"Réckmeldungen um PC gespäichert, am Dossier retours.", zh:"反馈已保存到电脑的 retours 文件夹。"},
  storeLocal:   {en:"Feedback kept in this browser. Start serveur.py on the PC so Claude can read it.", de:"Rückmeldungen bleiben in diesem Browser. Starten Sie serveur.py auf dem PC, damit Claude sie lesen kann.",
                 lb:"D'Réckmeldunge bleiwen an dësem Browser. Start serveur.py um PC, fir datt de Claude se liese kann.", zh:"反馈保存在此浏览器中。在电脑上运行 serveur.py，Claude 才能读取。"},
  // parents' corner
  parentsTitle: {en:"Parents' corner", de:"Elternbereich", lb:"Eltereneck", zh:"家长专区"},
  exportBtn:    {en:"Export feedback", de:"Rückmeldungen exportieren", lb:"Réckmeldungen exportéieren", zh:"导出反馈"},
  pending:      {en:n => `${n} item(s) waiting to be sent.`, de:n => `Noch nicht gesendet: ${n}.`, lb:n => `Nach net geschéckt: ${n}.`, zh:n => `${n}条待发送。`},
  present:      {en:"I'm playing with them right now", de:"Ich spiele gerade mit ihnen", lb:"Ech spille grad mat hinnen", zh:"我正在陪他们玩"},
  presentHelp:  {en:"Each game is marked “with a parent” or “alone”. It shows what works without you.", de:"Jede Partie wird als „mit Eltern“ oder „allein“ vermerkt. So sieht man, was ohne Sie funktioniert.",
                 lb:"All Partie gëtt als „mat Elteren“ oder „eleng“ markéiert. Esou gesäit een, wat ouni Iech funktionéiert.", zh:"每局都会标注“家长陪同”或“独自”，便于看出哪些游戏孩子能独立完成。"},
  presentOn:    {en:"Noted: you are playing with them", de:"Notiert: Sie spielen mit ihnen", lb:"Notéiert: Dir spillt mat hinnen", zh:"已记录：您在陪他们玩"},
  presentOff:   {en:"Noted: they play alone", de:"Notiert: Die Kinder spielen allein", lb:"Notéiert: si spillen eleng", zh:"已记录：他们独自玩"},
  progress:     {en:"Progress", de:"Fortschritt", lb:"Fortschrëtt", zh:"进度"},
  persistYes:   {en:"This browser protects the progress: it is not deleted to free space.", de:"Dieser Browser schützt den Fortschritt: Er wird nicht gelöscht, um Platz zu schaffen.",
                 lb:"Dëse Browser schützt de Fortschrëtt: e gëtt net geläscht, fir Plaz ze maachen.", zh:"此浏览器会保护进度：不会为腾出空间而删除。"},
  persistNo:    {en:"This browser may delete the progress when space runs low. Install the app or keep a backup.", de:"Dieser Browser kann den Fortschritt bei Platzmangel löschen. Installieren Sie die App oder legen Sie eine Sicherung an.",
                 lb:"Dëse Browser kann de Fortschrëtt läschen, wann d'Plaz knapp gëtt. Installéiert d'App oder maacht e Backup.", zh:"空间不足时，此浏览器可能会删除进度。请安装应用或保留备份。"},
  install:      {en:"Install the app on this device", de:"App auf diesem Gerät installieren", lb:"D'App op dësem Apparat installéieren", zh:"在此设备上安装应用"},
  installed:    {en:"App installed on the home screen", de:"App auf dem Startbildschirm installiert", lb:"App um Startbildschierm installéiert", zh:"应用已安装到主屏幕"},
  saveProg:     {en:"Save progress", de:"Fortschritt sichern", lb:"Fortschrëtt späicheren", zh:"保存进度"},
  restoreProg:  {en:"Restore a backup", de:"Sicherung wiederherstellen", lb:"Backup restauréieren", zh:"恢复备份"},
  savedDl:      {en:"Backup saved in Downloads", de:"Sicherung in Downloads gespeichert", lb:"Backup an den Downloads gespäichert", zh:"备份已保存到“下载”"},
  restored:     {en:(a, b) => `Progress restored: ⭐ ${a} and ⭐ ${b}`, de:(a, b) => `Fortschritt wiederhergestellt: ⭐ ${a} und ⭐ ${b}`,
                 lb:(a, b) => `Fortschrëtt restauréiert: ⭐ ${a} an ⭐ ${b}`, zh:(a, b) => `进度已恢复：⭐ ${a} 和 ⭐ ${b}`},
  notBackup:    {en:"This file is not a Word Island backup", de:"Diese Datei ist keine Sicherung der Wörterinsel", lb:"Dëse Fichier ass kee Backup vun der Wierderinsel", zh:"此文件不是单词岛的备份"},
  exportReady:  {en:"File ready: put it in ile-aux-mots/retours", de:"Datei bereit: in ile-aux-mots/retours ablegen", lb:"Fichier prett: an ile-aux-mots/retours leeën", zh:"文件已准备好：放入 ile-aux-mots/retours"},
  playTime:     {en:"Play time", de:"Spielzeit", lb:"Spillzäit", zh:"游戏时间"},
  playTimeHelp: {en:"Where each child spends time, most played game first (on this device).", de:"Wo jedes Kind seine Zeit verbringt, das meistgespielte Spiel zuerst (auf diesem Gerät).",
                 lb:"Wou all Kand seng Zäit verbréngt, dat Spill, dat am meeschte gespillt gouf, als éischt (op dësem Apparat).", zh:"每个孩子把时间花在哪里，玩得最多的排在前面（仅限此设备）。"},
  noPlayHere:   {en:"No game on this device yet.", de:"Noch kein Spiel auf diesem Gerät.", lb:"Nach keng Partie op dësem Apparat.", zh:"此设备上还没有游戏记录。"},
  timeHead:     {en:["Child","Game","Time","Games","Finished","Record","Level"], de:["Kind","Spiel","Zeit","Partien","Beendet","Rekord","Stufe"],
                 lb:["Kand","Spill","Zäit","Partien","Fäerdeg","Rekord","Niveau"], zh:["孩子","游戏","时间","局数","完成","纪录","级别"]},
  levels:       {en:"Levels", de:"Stufen", lb:"Niveauen", zh:"级别"},
  levelsHelp:   {en:"They go up and down on their own with success. You can adjust them.", de:"Die Stufen steigen und sinken je nach Erfolg von selbst. Sie können sie anpassen.",
                 lb:"Si ginn eleng erop an erof, jee no Erfolleg. Dir kënnt se upassen.", zh:"级别会根据表现自动升降，您也可以手动调整。"},
  game:         {en:"Game", de:"Spiel", lb:"Spill", zh:"游戏"},
  lower:        {en:g => `Lower the level of ${g}`, de:g => `Stufe von ${g} senken`, lb:g => `Niveau vun ${g} erofsetzen`, zh:g => `降低${g}的级别`},
  raise:        {en:g => `Raise the level of ${g}`, de:g => `Stufe von ${g} erhöhen`, lb:g => `Niveau vun ${g} erhéijen`, zh:g => `提高${g}的级别`},
  children:     {en:"The children", de:"Die Kinder", lb:"D'Kanner", zh:"孩子们"},
  save:         {en:"Save", de:"Speichern", lb:"Späicheren", zh:"保存"},
  namesSaved:   {en:"Names saved", de:"Namen gespeichert", lb:"Nimm gespäichert", zh:"名字已保存"},
  yourFeedback: {en:"Your feedback", de:"Ihre Rückmeldung", lb:"Är Réckmeldung", zh:"您的反馈"},
  feedbackHelp: {en:"What they liked, what got stuck, a bug, an idea. Claude reads these notes to improve the site.", de:"Was gefallen hat, was gehakt hat, ein Fehler, eine Idee. Claude liest diese Notizen, um die Seite zu verbessern.",
                 lb:"Wat gefall huet, wat gehaangen huet, e Feeler, eng Iddi. De Claude liest dës Notizen, fir de Site ze verbesseren.", zh:"喜欢什么、哪里卡住、错误或想法。Claude 会阅读这些留言来改进网站。"},
  about:        {en:"About", de:"Thema", lb:"Thema", zh:"关于"},
  forWhom:      {en:"For", de:"Für", lb:"Fir", zh:"针对"},
  both:         {en:"both", de:"beide", lb:"alle béid", zh:"两个孩子"},
  general:      {en:"The site in general", de:"Die Seite allgemein", lb:"De Site allgemeng", zh:"整个网站"},
  generalShort: {en:"General", de:"Allgemein", lb:"Allgemeng", zh:"总体"},
  feedbackPh:   {en:"E.g.: the little one loved the balloons but doesn't understand “purple”", de:"Z. B.: Die Kleine fand die Ballons toll, versteht aber „lila“ nicht",
                 lb:"Z. B.: D'Kleng hat d'Ballone gär, mee si versteet „mof“ net", zh:"例如：妹妹很喜欢气球，但听不懂“紫色”"},
  send:         {en:"Send feedback", de:"Rückmeldung senden", lb:"Réckmeldung schécken", zh:"发送反馈"},
  pickTag:      {en:"Choose a tag or write a word", de:"Wählen Sie ein Stichwort oder schreiben Sie etwas", lb:"Wielt e Stéchwuert oder schreift eppes", zh:"请选择一个标签或写几个字"},
  thanksNote:   {en:"Thank you! Claude will read it.", de:"Danke! Claude wird es lesen.", lb:"Merci! De Claude liest et.", zh:"谢谢！Claude 会阅读。"},
  whatWorks:    {en:"What works", de:"Was funktioniert", lb:"Wat funktionéiert", zh:"哪些有效"},
  noSessions:   {en:"No game played yet. Figures will appear here after the first games.", de:"Noch kein Spiel gespielt. Die Zahlen erscheinen hier nach den ersten Spielen.",
                 lb:"Nach keng Partie gespillt. D'Zuelen erschéngen hei no den éischte Partien.", zh:"还没有玩过游戏。玩过几局后，这里会显示数据。"},
  notPlayed:    {en:"not played yet", de:"noch nicht gespielt", lb:"nach net gespillt", zh:"还没玩过"},
  statsHead:    {en:["Game","Games","Finished","First try","Children's rating","Avg. time"], de:["Spiel","Partien","Beendet","Beim 1. Mal","Bewertung der Kinder","Ø Dauer"],
                 lb:["Spill","Partien","Fäerdeg","Beim 1. Mol","Bewäertung vun de Kanner","Ø Dauer"], zh:["游戏","局数","完成","一次答对","孩子评价","平均时长"]},
  hardWords:    {en:"Words that resist", de:"Schwierige Wörter", lb:"Schwiereg Wierder", zh:"难记的单词"},
  nothing:      {en:"Nothing to report yet.", de:"Noch nichts zu melden.", lb:"Nach näischt ze mellen.", zh:"暂时没有需要注意的。"},
  missed:       {en:p => `${p} % missed`, de:p => `${p} % falsch`, lb:p => `${p} % falsch`, zh:p => `错${p}%`},
  lastNotes:    {en:"Latest feedback", de:"Letzte Rückmeldungen", lb:"Lescht Réckmeldungen", zh:"最近的反馈"},
  noNotes:      {en:"No written feedback yet.", de:"Noch keine schriftliche Rückmeldung.", lb:"Nach keng schrëftlech Réckmeldung.", zh:"还没有书面反馈。"},
  handled:      {en:"✅ handled", de:"✅ erledigt", lb:"✅ erleedegt", zh:"✅ 已处理"},
  // feedback tags, same order as FB_TAGS (the stored value stays FB_TAGS, for Claude)
  fbTags:       {en:["Loved it","Too easy","Too hard","Bored","Sound / voice","Bug","Idea"], de:["Begeistert","Zu leicht","Zu schwer","Langeweile","Ton / Stimme","Fehler","Idee"],
                 lb:["Begeeschtert","Ze liicht","Ze schwéier","Langweil","Toun / Stëmm","Feeler","Iddi"], zh:["很喜欢","太简单","太难","无聊","声音","错误","想法"]}
};
const THEME_LABELS = {
  animals:{en:"Animals", de:"Tiere", lb:"Déieren", zh:"动物"}, food:{en:"Food", de:"Essen", lb:"Iessen", zh:"食物"},
  colors:{en:"Colours", de:"Farben", lb:"Faarwen", zh:"颜色"}, body:{en:"My body", de:"Mein Körper", lb:"Mäi Kierper", zh:"我的身体"},
  things:{en:"My world", de:"Meine Welt", lb:"Meng Welt", zh:"身边的东西"}, clothes:{en:"Clothes", de:"Kleidung", lb:"Kleeder", zh:"衣服"},
  jobs:{en:"Jobs", de:"Berufe", lb:"Beruffer", zh:"职业"}, actions:{en:"Actions", de:"Was ich mache", lb:"Wat ech maachen", zh:"动作"}
};
// island titles for games that do not declare meta.title themselves: [title, subtitle]
const GAME_TITLES = {
  imagier:{en:["Picture book","Tap a picture, it talks"], de:["Bilderbuch","Tipp auf ein Bild, es spricht"], lb:["Billerbuch","Tipp op e Bild, et schwätzt"], zh:["看图识字","点一点图片，它会说话"]},
  ecoute:{en:["Listen & find","Find the right picture"], de:["Hör zu & finde","Finde das richtige Bild"], lb:["Lauschter a fann","Fann dat richtegt Bild"], zh:["听一听，找一找","找到正确的图片"]},
  ballons:{en:["Balloons","Pop the right colour"], de:["Ballons","Lass die richtige Farbe platzen"], lb:["Ballonen","Looss déi richteg Faarf platzen"], zh:["气球","戳破颜色对的气球"]},
  compte:{en:["Maths","Count and calculate"], de:["Rechnen","Zählen und rechnen"], lb:["Rechnen","Zielen a rechnen"], zh:["算一算","数数和计算"]},
  memory:{en:["Memory","Find the pairs"], de:["Memory","Finde die Paare"], lb:["Memory","Fann d'Puerer"], zh:["记忆翻牌","找出成对的牌"]},
  simon:{en:["Simon says","Move your body"], de:["Simon sagt","Beweg dich"], lb:["De Simon seet","Beweeg dech"], zh:["西蒙说","动动身体"]},
  repete:{en:["Say it!","Say the word out loud"], de:["Sag es!","Sag das Wort laut"], lb:["So et!","So d'Wuert haart"], zh:["说一说","大声说出这个词"]},
  alphabet:{en:["ABC","Letters and their sounds"], de:["ABC","Buchstaben und ihre Laute"], lb:["ABC","Buschtawen an hir Lauter"], zh:["拼音","字母和发音"]},
  cachecache:{en:["Hide & seek","Where is the cat?"], de:["Verstecken","Wo ist die Katze?"], lb:["Verstoppches","Wou ass d'Kaz?"], zh:["捉迷藏","猫在哪里？"]},
  calendrier:{en:["Calendar","Days, months, seasons"], de:["Kalender","Tage, Monate, Jahreszeiten"], lb:["Kalenner","Deeg, Méint, Joreszäiten"], zh:["日历","星期、月份、季节"]},
  coloriage:{en:["Colouring","Colour what you hear"], de:["Ausmalen","Mal aus, was du hörst"], lb:["Fierwen","Fierf, wat s de héiers"], zh:["涂颜色","听到什么就涂什么"]},
  contraires:{en:["Opposites","Big, small, hot, cold"], de:["Gegenteile","Groß, klein, heiß, kalt"], lb:["Géigendeeler","Grouss, kleng, waarm, kal"], zh:["反义词","大和小，冷和热"]},
  emotions:{en:["Feelings","How do you feel?"], de:["Gefühle","Wie fühlst du dich?"], lb:["Gefiller","Wéi fills du dech?"], zh:["心情","你感觉怎么样？"]},
  formes:{en:["Shapes","Circle, square, star…"], de:["Formen","Kreis, Quadrat, Stern…"], lb:["Formen","Krees, Quadrat, Stär…"], zh:["形状","圆形、正方形、星形……"]},
  heure:{en:["What time is it?","Read the clock"], de:["Wie spät ist es?","Die Uhr lesen"], lb:["Wéi vill Auer ass et?","D'Auer liesen"], zh:["几点了？","看钟表"]},
  loup:{en:["Mr Wolf","What's the time?"], de:["Herr Wolf","Wie spät ist es?"], lb:["Här Wollef","Wéi vill Auer ass et?"], zh:["老狼","老狼老狼几点了？"]},
  machine:{en:["Word machine","Rhymes and sounds"], de:["Wörtermaschine","Reime und Laute"], lb:["Wierdermaschinn","Reimer a Lauter"], zh:["词语机器","押韵和发音"]},
  manque:{en:["What's missing?","Remember the magician's things"], de:["Was fehlt?","Merk dir die Sachen des Zauberers"], lb:["Wat feelt?","Mierk der d'Saache vum Zauberer"], zh:["少了什么？","记住魔术师的东西"]},
  marche:{en:["Market","Sell fruit and count money"], de:["Markt","Obst verkaufen und Geld zählen"], lb:["Maart","Uebst verkafen a Suen zielen"], zh:["市场","卖水果，数钱"]},
  pays:{en:["Flags","Countries of the world"], de:["Flaggen","Länder der Welt"], lb:["Fändelen","Länner vun der Welt"], zh:["国旗","世界各国"]},
  suites:{en:["Patterns","What comes next?"], de:["Muster","Was kommt als Nächstes?"], lb:["Muster","Wat kënnt duerno?"], zh:["找规律","下一个是什么？"]},
  vraifaux:{en:["True or false?","Listen or read the sentence"], de:["Richtig oder falsch?","Hör zu oder lies den Satz"], lb:["Richteg oder falsch?","Lauschter oder lies de Saz"], zh:["对还是错？","听一听或读一读句子"]}
};
